/* Matchday Workforce — mock data */
const MW = {
  operator: {
    name: 'Matchday Workforce',
    legal: 'Operated by Matchday Workforce LLC — an independent stadium staffing & recruitment platform. Not affiliated with Major League Soccer or any MLS club unless listed as a partner employer.',
  },

  marketRegions: [
    {
      label: 'Pacific Northwest',
      cities: [
        { city: 'Portland', state: 'OR' },
        { city: 'Seattle', state: 'WA' },
        { city: 'Vancouver', state: 'BC' },
      ],
    },
    {
      label: 'California',
      cities: [
        { city: 'Los Angeles', state: 'CA' },
        { city: 'Carson', state: 'CA' },
        { city: 'San Diego', state: 'CA' },
        { city: 'San Jose', state: 'CA' },
      ],
    },
    {
      label: 'Mountain & Southwest',
      cities: [
        { city: 'Austin', state: 'TX' },
        { city: 'Frisco', state: 'TX' },
        { city: 'Houston', state: 'TX' },
        { city: 'Kansas City', state: 'KS' },
        { city: 'Commerce City', state: 'CO' },
        { city: 'Sandy', state: 'UT' },
      ],
    },
    {
      label: 'Southeast',
      cities: [
        { city: 'Atlanta', state: 'GA' },
        { city: 'Charlotte', state: 'NC' },
        { city: 'Orlando', state: 'FL' },
        { city: 'Miami', state: 'FL' },
        { city: 'Fort Lauderdale', state: 'FL' },
        { city: 'Nashville', state: 'TN' },
      ],
    },
    {
      label: 'Midwest',
      cities: [
        { city: 'Chicago', state: 'IL' },
        { city: 'Cincinnati', state: 'OH' },
        { city: 'Columbus', state: 'OH' },
        { city: 'St. Paul', state: 'MN' },
        { city: 'St. Louis', state: 'MO' },
      ],
    },
    {
      label: 'Northeast & Canada',
      cities: [
        { city: 'Foxborough', state: 'MA' },
        { city: 'New York', state: 'NY' },
        { city: 'Harrison', state: 'NJ' },
        { city: 'Chester', state: 'PA' },
        { city: 'Washington', state: 'DC' },
        { city: 'Toronto', state: 'ON' },
        { city: 'Montreal', state: 'QC' },
      ],
    }
  ],

  stadiums: [
    {
      id: 'mercedes-benz-stadium',
      image: 'Stadiums.jpg/Mercedes benz stadium.jpg',
      name: 'Mercedes-Benz Stadium',
      club: 'Atlanta United FC',
      city: 'Atlanta',
      state: 'GA',
      matches: [],
    },
    {
      id: 'bank-of-america-stadium',
      image: 'Stadiums.jpg/Bank Of America Stadium.jpg',
      name: 'Bank of America Stadium',
      club: 'Charlotte FC',
      city: 'Charlotte',
      state: 'NC',
      matches: [],
    },
    {
      id: 'interco-stadium',
      image: 'Stadiums.jpg/Inter&Co Stadium.jpg',
      name: 'Inter&Co Stadium',
      club: 'Orlando City SC',
      city: 'Orlando',
      state: 'FL',
      matches: [],
    },
    {
      id: 'stade-saputo',
      image: 'Stadiums.jpg/Stade Saputo stadium.jpg',
      name: 'Stade Saputo',
      club: 'CF Montréal',
      city: 'Montreal',
      state: 'QC',
      matches: [],
    },
    {
      id: 'bmo-field',
      image: 'Stadiums.jpg/BMO Field.jpg',
      name: 'BMO Field',
      club: 'Toronto FC',
      city: 'Toronto',
      state: 'ON',
      matches: [],
    },
    {
      id: 'shell-energy-stadium',
      image: 'Stadiums.jpg/Shell Energy Stadium.webp',
      name: 'Shell Energy Stadium',
      club: 'Houston Dynamo FC',
      city: 'Houston',
      state: 'TX',
      matches: [],
    },
    {
      id: 'geodis-park',
      image: 'Stadiums.jpg/Geodis Park.jpg',
      name: 'GEODIS Park',
      club: 'Nashville SC',
      city: 'Nashville',
      state: 'TN',
      matches: [],
    },
    {
      id: 'dicks-sporting-goods-park',
      image: 'Stadiums.jpg/Dick\'s Sporting goods park.jpg',
      name: 'Dick\'s Sporting Goods Park',
      club: 'Colorado Rapids',
      city: 'Commerce City',
      state: 'CO',
      matches: [],
    },
    {
      id: 'america-first-field',
      image: 'Stadiums.jpg/America First Field.jpg',
      name: 'America First Field',
      club: 'Real Salt Lake',
      city: 'Sandy',
      state: 'UT',
      matches: [],
    },
    {
      id: 'bmo-stadium',
      image: 'Stadiums.jpg/BMO Stadium.jpg',
      name: 'BMO Stadium',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      matches: [],
    },
    {
      id: 'paypal-park',
      image: 'Stadiums.jpg/PayPal Park.jpg',
      name: 'PayPal Park',
      club: 'San Jose Earthquakes',
      city: 'San Jose',
      state: 'CA',
      matches: [],
    },
    {
      id: 'soldier-field',
      image: 'Stadiums.jpg/Soldier field stadium.jpg',
      name: 'Soldier Field',
      club: 'Chicago Fire FC',
      city: 'Chicago',
      state: 'IL',
      matches: [],
    },
    {
      id: 'yankee-stadium',
      image: 'Stadiums.jpg/Etihad Park.jpg',
      name: 'Yankee Stadium',
      club: 'New York City FC',
      city: 'New York',
      state: 'NY',
      matches: [],
    },
    {
      id: 'q2-stadium',
      image: 'Stadiums.jpg/Q2 stadium.jpg',
      name: 'Q2 Stadium',
      club: 'Austin FC',
      city: 'Austin',
      state: 'TX',
      matches: [],
    },
    {
      id: 'lumen-field',
      image: 'Stadiums.jpg/Lumen Field.jpg',
      name: 'Lumen Field',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      matches: [],
    },
    {
      id: 'tql-stadium',
      image: 'Stadiums.jpg/TQL Stadium.jpg',
      name: 'TQL Stadium',
      club: 'FC Cincinnati',
      city: 'Cincinnati',
      state: 'OH',
      matches: [],
    },
    {
      id: 'audi-field',
      image: 'Stadiums.jpg/Audi Stadium.jpg',
      name: 'Audi Field',
      club: 'D.C. United',
      city: 'Washington',
      state: 'DC',
      matches: [],
    },
    {
      id: 'red-bull-arena',
      image: 'Stadiums.jpg/Red Bull Arena.jpg',
      name: 'Red Bull Arena',
      club: 'New York Red Bulls',
      city: 'Harrison',
      state: 'NJ',
      matches: [],
    },
    {
      id: 'subaru-park',
      image: 'Stadiums.jpg/Subaru Park.jpg',
      name: 'Subaru Park',
      club: 'Philadelphia Union',
      city: 'Chester',
      state: 'PA',
      matches: [],
    },
    {
      id: 'scottsmiracle-gro-field',
      image: 'Stadiums.jpg/Lower.com Field.jpg',
      name: 'ScottsMiracle-Gro Field',
      club: 'Columbus Crew',
      city: 'Columbus',
      state: 'OH',
      matches: [],
    },
    {
      id: 'childrens-mercy-park',
      image: 'Stadiums.jpg/Children\'s Mercy Park.jpg',
      name: 'Children\'s Mercy Park',
      club: 'Sporting Kansas City',
      city: 'Kansas City',
      state: 'KS',
      matches: [],
    },
    {
      id: 'allianz-field',
      image: 'Stadiums.jpg/Allainz field.jpg',
      name: 'Allianz Field',
      club: 'Minnesota United FC',
      city: 'St. Paul',
      state: 'MN',
      matches: [],
    },
    {
      id: 'dignity-health-sports-park',
      image: 'Stadiums.jpg/Dignity Health Stadium.webp',
      name: 'Dignity Health Sports Park',
      club: 'LA Galaxy',
      city: 'Carson',
      state: 'CA',
      matches: [],
    },
    {
      id: 'providence-park',
      image: 'Stadiums.jpg/Providence Park.jpg',
      name: 'Providence Park',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      matches: [],
    },
    {
      id: 'bc-place',
      image: 'Stadiums.jpg/BC Place.jpg',
      name: 'BC Place',
      club: 'Vancouver Whitecaps FC',
      city: 'Vancouver',
      state: 'BC',
      matches: [],
    },
    {
      id: 'chase-stadium',
      image: 'Stadiums.jpg/Chase Stadium.jpg',
      name: 'Chase Stadium',
      club: 'Inter Miami CF',
      city: 'Fort Lauderdale',
      state: 'FL',
      matches: [],
    },
    {
      id: 'nu-stadium',
      image: 'Stadiums.jpg/Chase Stadium.jpg',
      name: 'Nu Stadium',
      club: 'Inter Miami CF',
      city: 'Miami',
      state: 'FL',
      matches: [],
    },
    {
      id: 'gillette-stadium',
      image: 'Stadiums.jpg/Gillete stadium.jpg',
      name: 'Gillette Stadium',
      club: 'New England Revolution',
      city: 'Foxborough',
      state: 'MA',
      matches: [],
    },
    {
      id: 'energizer-park',
      image: 'Stadiums.jpg/CITYPARK.webp',
      name: 'Energizer Park',
      club: 'St. Louis CITY SC',
      city: 'St. Louis',
      state: 'MO',
      matches: [],
    },
    {
      id: 'snapdragon-stadium',
      image: 'Stadiums.jpg/Snapdragon Stadium.webp',
      name: 'Snapdragon Stadium',
      club: 'San Diego FC',
      city: 'San Diego',
      state: 'CA',
      matches: [],
    },
    {
      id: 'toyota-stadium',
      image: 'Stadiums.jpg/Toyota Stadium.jpg',
      name: 'Toyota Stadium',
      club: 'FC Dallas',
      city: 'Frisco',
      state: 'TX',
      matches: [],
    }
  ],
  jobs: [],

  matchRoles: [
    { id: 'guest-services', title: 'Guest Services Associate', category: 'Guest Services', type: 'Event-based', payMin: 24, payMax: 30, payLabel: '$24–$30 / hr', slots: 28 },
    { id: 'ushering', title: 'Matchday Usher', category: 'Ushering', type: 'Event-based', payMin: 23, payMax: 28, payLabel: '$23–$28 / hr', slots: 32 },
    { id: 'ticket-scanning', title: 'Ticket Scanner', category: 'Ticket Scanning', type: 'Event-based', payMin: 23, payMax: 27, payLabel: '$23–$27 / hr', slots: 18 },
    { id: 'bag-check', title: 'Bag Check Associate', category: 'Bag Check & Screening', type: 'Event-based', payMin: 25, payMax: 30, payLabel: '$25–$30 / hr', slots: 16 },
    { id: 'security', title: 'Event Security Officer', category: 'Security', type: 'Event-based', payMin: 28, payMax: 36, payLabel: '$28–$36 / hr', slots: 22 },
    { id: 'concessions', title: 'Concessions Team Member', category: 'Concessions', type: 'Event-based', payMin: 22, payMax: 28, payLabel: '$22–$28 / hr + tips where offered', slots: 40 },
    { id: 'bartending', title: 'Matchday Bartender', category: 'Bartending', type: 'Event-based', payMin: 24, payMax: 32, payLabel: '$24–$32 / hr + tips', slots: 12 },
    { id: 'retail', title: 'Team Store Associate', category: 'Retail / Team Store', type: 'Event-based', payMin: 23, payMax: 29, payLabel: '$23–$29 / hr', slots: 14 },
    { id: 'hospitality', title: 'Suite Attendant', category: 'Hospitality & Suites', type: 'Event-based', payMin: 26, payMax: 34, payLabel: '$26–$34 / hr', slots: 10 },
    { id: 'premium', title: 'Club Level Host', category: 'Club & Premium Experience', type: 'Event-based', payMin: 27, payMax: 35, payLabel: '$27–$35 / hr', slots: 8 },
    { id: 'parking', title: 'Parking Attendant', category: 'Parking & Traffic', type: 'Event-based', payMin: 22, payMax: 26, payLabel: '$22–$26 / hr', slots: 20 },
    { id: 'cleaning', title: 'Event Cleaner', category: 'Cleaning & Housekeeping', type: 'Event-based', payMin: 22, payMax: 27, payLabel: '$22–$27 / hr', slots: 24 },
    { id: 'event-ops', title: 'Event Operations Crew', category: 'Event Operations', type: 'Event-based', payMin: 25, payMax: 32, payLabel: '$25–$32 / hr', slots: 15 },
    { id: 'field-ops', title: 'Field Operations Crew', category: 'Field Operations', type: 'Event-based', payMin: 26, payMax: 34, payLabel: '$26–$34 / hr', slots: 6 },
    { id: 'medical', title: 'First Aid / Medical Support', category: 'Medical & First Aid', type: 'Event-based', payMin: 32, payMax: 42, payLabel: '$32–$42 / hr', slots: 4 },
    { id: 'warehouse', title: 'Warehouse & Logistics', category: 'Warehouse & Logistics', type: 'Event-based', payMin: 24, payMax: 30, payLabel: '$24–$30 / hr', slots: 8 },
    { id: 'box-office', title: 'Box Office / Will Call', category: 'Box Office / Will Call', type: 'Event-based', payMin: 23, payMax: 29, payLabel: '$23–$29 / hr', slots: 6 },
  ],

  clubJobs: [
    {
      id: 'cj-atl-marketing',
      title: 'Specialist, Digital Marketing',
      club: 'Atlanta United FC',
      city: 'Atlanta',
      state: 'GA',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Marketing',
    },
    {
      id: 'cj-atl-tickets',
      title: 'Account Executive, Season Ticket Sales',
      club: 'Atlanta United FC',
      city: 'Atlanta',
      state: 'GA',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-atl-community',
      title: 'Coordinator, Community Relations',
      club: 'Atlanta United FC',
      city: 'Atlanta',
      state: 'GA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-atl-premium',
      title: 'Manager, Premium Seating',
      club: 'Atlanta United FC',
      city: 'Atlanta',
      state: 'GA',
      type: 'Full-time',
      level: 'Manager',
      category: 'Premium Sales',
    },
    {
      id: 'cj-atx-partnerships',
      title: 'Coordinator, Corporate Partnerships',
      club: 'Austin FC',
      city: 'Austin',
      state: 'TX',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Partnerships',
    },
    {
      id: 'cj-atx-content',
      title: 'Producer, Content & Social Media',
      club: 'Austin FC',
      city: 'Austin',
      state: 'TX',
      type: 'Full-time',
      level: 'Producer',
      category: 'Marketing',
    },
    {
      id: 'cj-atx-ops',
      title: 'Assistant, Stadium Operations',
      club: 'Austin FC',
      city: 'Austin',
      state: 'TX',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-atx-retail',
      title: 'Lead, Matchday Retail',
      club: 'Austin FC',
      city: 'Austin',
      state: 'TX',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Retail',
    },
    {
      id: 'cj-mtl-bilingual',
      title: 'Coordinator, Fan Services (Bilingual)',
      club: 'CF Montréal',
      city: 'Montreal',
      state: 'QC',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Guest Experience',
    },
    {
      id: 'cj-mtl-tickets',
      title: 'Representative, Ticket Sales',
      club: 'CF Montréal',
      city: 'Montreal',
      state: 'QC',
      type: 'Full-time',
      level: 'Representative',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-mtl-academy',
      title: 'Administrator, Academy Operations',
      club: 'CF Montréal',
      city: 'Montreal',
      state: 'QC',
      type: 'Full-time',
      level: 'Administrator',
      category: 'Academy',
    },
    {
      id: 'cj-clt-sales',
      title: 'Manager, Group Sales',
      club: 'Charlotte FC',
      city: 'Charlotte',
      state: 'NC',
      type: 'Full-time',
      level: 'Manager',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-clt-hr',
      title: 'Specialist, People & Culture',
      club: 'Charlotte FC',
      city: 'Charlotte',
      state: 'NC',
      type: 'Full-time',
      level: 'Specialist',
      category: 'People & Culture',
    },
    {
      id: 'cj-clt-events',
      title: 'Coordinator, Event Operations',
      club: 'Charlotte FC',
      city: 'Charlotte',
      state: 'NC',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-clt-pr',
      title: 'Coordinator, Communications',
      club: 'Charlotte FC',
      city: 'Charlotte',
      state: 'NC',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Communications',
    },
    {
      id: 'cj-fire-foundation',
      title: 'Manager of Programming, Chicago Fire Foundation',
      club: 'Chicago Fire FC',
      city: 'Chicago',
      state: 'IL',
      type: 'Full-time',
      level: 'Manager',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-fire-analytics',
      title: 'Analyst, Business Intelligence',
      club: 'Chicago Fire FC',
      city: 'Chicago',
      state: 'IL',
      type: 'Full-time',
      level: 'Analyst',
      category: 'Business Operations',
    },
    {
      id: 'cj-fire-youth',
      title: 'Coordinator, Youth Soccer Programs',
      club: 'Chicago Fire FC',
      city: 'Chicago',
      state: 'IL',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-fire-hospitality',
      title: 'Supervisor, Matchday Hospitality',
      club: 'Chicago Fire FC',
      city: 'Chicago',
      state: 'IL',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Hospitality',
    },
    {
      id: 'cj-col-tickets',
      title: 'Account Executive, Membership Sales',
      club: 'Colorado Rapids',
      city: 'Commerce City',
      state: 'CO',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-col-ops',
      title: 'Manager, Facility Operations',
      club: 'Colorado Rapids',
      city: 'Commerce City',
      state: 'CO',
      type: 'Full-time',
      level: 'Manager',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-col-marketing',
      title: 'Coordinator, Brand Marketing',
      club: 'Colorado Rapids',
      city: 'Commerce City',
      state: 'CO',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Marketing',
    },
    {
      id: 'cj-clb-hr',
      title: 'Coordinator, People & Culture',
      club: 'Columbus Crew',
      city: 'Columbus',
      state: 'OH',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'People & Culture',
    },
    {
      id: 'cj-clb-partnerships',
      title: 'Manager, Partnership Activation',
      club: 'Columbus Crew',
      city: 'Columbus',
      state: 'OH',
      type: 'Full-time',
      level: 'Manager',
      category: 'Partnerships',
    },
    {
      id: 'cj-clb-academy',
      title: 'Coordinator, Crew Academy',
      club: 'Columbus Crew',
      city: 'Columbus',
      state: 'OH',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Academy',
    },
    {
      id: 'cj-clb-retail',
      title: 'Associate, Team Store',
      club: 'Columbus Crew',
      city: 'Columbus',
      state: 'OH',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Retail',
    },
    {
      id: 'cj-dc-comms',
      title: 'Specialist, Media Relations',
      club: 'D.C. United',
      city: 'Washington',
      state: 'DC',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Communications',
    },
    {
      id: 'cj-dc-tickets',
      title: 'Manager, Season Ticket Member Services',
      club: 'D.C. United',
      city: 'Washington',
      state: 'DC',
      type: 'Full-time',
      level: 'Manager',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-dc-security',
      title: 'Supervisor, Stadium Security',
      club: 'D.C. United',
      city: 'Washington',
      state: 'DC',
      type: 'Full-time',
      level: 'Supervisor',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-dc-front',
      title: 'Assistant, Front Office Administration',
      club: 'D.C. United',
      city: 'Washington',
      state: 'DC',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Front Office',
    },
    {
      id: 'cj-cin-sales',
      title: 'Account Executive, Corporate Sales',
      club: 'FC Cincinnati',
      city: 'Cincinnati',
      state: 'OH',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Partnerships',
    },
    {
      id: 'cj-cin-guest',
      title: 'Manager, Guest Experience',
      club: 'FC Cincinnati',
      city: 'Cincinnati',
      state: 'OH',
      type: 'Full-time',
      level: 'Manager',
      category: 'Guest Experience',
    },
    {
      id: 'cj-cin-content',
      title: 'Editor, Digital Content',
      club: 'FC Cincinnati',
      city: 'Cincinnati',
      state: 'OH',
      type: 'Full-time',
      level: 'Editor',
      category: 'Marketing',
    },
    {
      id: 'cj-cin-ops',
      title: 'Coordinator, Matchday Operations',
      club: 'FC Cincinnati',
      city: 'Cincinnati',
      state: 'OH',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-fcd-academy',
      title: 'Manager, Academy Recruitment',
      club: 'FC Dallas',
      city: 'Frisco',
      state: 'TX',
      type: 'Full-time',
      level: 'Manager',
      category: 'Academy',
    },
    {
      id: 'cj-fcd-tickets',
      title: 'Representative, Inside Sales',
      club: 'FC Dallas',
      city: 'Frisco',
      state: 'TX',
      type: 'Full-time',
      level: 'Representative',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-fcd-finance',
      title: 'Analyst, Finance',
      club: 'FC Dallas',
      city: 'Frisco',
      state: 'TX',
      type: 'Full-time',
      level: 'Analyst',
      category: 'Business Operations',
    },
    {
      id: 'cj-fcd-events',
      title: 'Coordinator, Special Events',
      club: 'FC Dallas',
      city: 'Frisco',
      state: 'TX',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-hou-partnerships',
      title: 'Coordinator, Sponsor Services',
      club: 'Houston Dynamo FC',
      city: 'Houston',
      state: 'TX',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Partnerships',
    },
    {
      id: 'cj-hou-community',
      title: 'Manager, Community Outreach',
      club: 'Houston Dynamo FC',
      city: 'Houston',
      state: 'TX',
      type: 'Full-time',
      level: 'Manager',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-hou-ops',
      title: 'Technician, Stadium Operations',
      club: 'Houston Dynamo FC',
      city: 'Houston',
      state: 'TX',
      type: 'Full-time',
      level: 'Technician',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-hou-tickets',
      title: 'Account Executive, Group Tickets',
      club: 'Houston Dynamo FC',
      city: 'Houston',
      state: 'TX',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-mia-retail',
      title: 'Associate, Retail Operations',
      club: 'Inter Miami CF',
      city: 'Fort Lauderdale',
      state: 'FL',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Retail',
    },
    {
      id: 'cj-mia-premium',
      title: 'Manager, Suite Sales & Service',
      club: 'Inter Miami CF',
      city: 'Fort Lauderdale',
      state: 'FL',
      type: 'Full-time',
      level: 'Manager',
      category: 'Premium Sales',
    },
    {
      id: 'cj-mia-marketing',
      title: 'Specialist, Social Media',
      club: 'Inter Miami CF',
      city: 'Fort Lauderdale',
      state: 'FL',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Marketing',
    },
    {
      id: 'cj-mia-hospitality',
      title: 'Coordinator, VIP Hospitality',
      club: 'Inter Miami CF',
      city: 'Fort Lauderdale',
      state: 'FL',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Hospitality',
    },
    {
      id: 'cj-mia-tickets',
      title: 'Account Executive, Membership Sales',
      club: 'Inter Miami CF',
      city: 'Fort Lauderdale',
      state: 'FL',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-lag-alumni',
      title: 'Coordinator, Alumni & Legends Relations',
      club: 'LA Galaxy',
      city: 'Carson',
      state: 'CA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-lag-tickets',
      title: 'Manager, Ticket Operations',
      club: 'LA Galaxy',
      city: 'Carson',
      state: 'CA',
      type: 'Full-time',
      level: 'Manager',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-lag-broadcast',
      title: 'Associate Producer, Broadcast',
      club: 'LA Galaxy',
      city: 'Carson',
      state: 'CA',
      type: 'Full-time',
      level: 'Associate Producer',
      category: 'Communications',
    },
    {
      id: 'cj-lag-retail',
      title: 'Supervisor, Team Store',
      club: 'LA Galaxy',
      city: 'Carson',
      state: 'CA',
      type: 'Full-time',
      level: 'Supervisor',
      category: 'Retail',
    },
    {
      id: 'cj-lafc-partnerships',
      title: 'Coordinator, Corporate Partnerships',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Partnerships',
    },
    {
      id: 'cj-lafc-strategy',
      title: 'Analyst, Strategy & Insights',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      type: 'Full-time',
      level: 'Analyst',
      category: 'Business Operations',
    },
    {
      id: 'cj-lafc-creative',
      title: 'Designer, Creative Services',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      type: 'Full-time',
      level: 'Designer',
      category: 'Marketing',
    },
    {
      id: 'cj-lafc-ops',
      title: 'Manager, Event Operations',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      type: 'Full-time',
      level: 'Manager',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-lafc-tickets',
      title: 'Account Executive, Premium Seating',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Premium Sales',
    },
    {
      id: 'cj-min-community',
      title: 'Coordinator, Loons Community Fund',
      club: 'Minnesota United FC',
      city: 'St. Paul',
      state: 'MN',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-min-sales',
      title: 'Account Executive, Season Tickets',
      club: 'Minnesota United FC',
      city: 'St. Paul',
      state: 'MN',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-min-ops',
      title: 'Assistant, Stadium Operations',
      club: 'Minnesota United FC',
      city: 'St. Paul',
      state: 'MN',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-min-marketing',
      title: 'Specialist, Email & CRM Marketing',
      club: 'Minnesota United FC',
      city: 'St. Paul',
      state: 'MN',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Marketing',
    },
    {
      id: 'cj-nsh-music',
      title: 'Coordinator, Entertainment & Matchday Presentation',
      club: 'Nashville SC',
      city: 'Nashville',
      state: 'TN',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-nsh-tickets',
      title: 'Manager, Membership Services',
      club: 'Nashville SC',
      city: 'Nashville',
      state: 'TN',
      type: 'Full-time',
      level: 'Manager',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-nsh-partnerships',
      title: 'Specialist, Partnership Marketing',
      club: 'Nashville SC',
      city: 'Nashville',
      state: 'TN',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Partnerships',
    },
    {
      id: 'cj-nsh-front',
      title: 'Assistant, Front Office',
      club: 'Nashville SC',
      city: 'Nashville',
      state: 'TN',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Front Office',
    },
    {
      id: 'cj-ne-academy',
      title: 'Coordinator, Revolution Academy',
      club: 'New England Revolution',
      city: 'Foxborough',
      state: 'MA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Academy',
    },
    {
      id: 'cj-ne-tickets',
      title: 'Account Executive, Ticket Sales',
      club: 'New England Revolution',
      city: 'Foxborough',
      state: 'MA',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-ne-ops',
      title: 'Supervisor, Event Staffing',
      club: 'New England Revolution',
      city: 'Foxborough',
      state: 'MA',
      type: 'Full-time',
      level: 'Supervisor',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-ne-comms',
      title: 'Coordinator, Public Relations',
      club: 'New England Revolution',
      city: 'Foxborough',
      state: 'MA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Communications',
    },
    {
      id: 'cj-nyc-partnerships',
      title: 'Manager, Corporate Partnerships',
      club: 'New York City FC',
      city: 'New York',
      state: 'NY',
      type: 'Full-time',
      level: 'Manager',
      category: 'Partnerships',
    },
    {
      id: 'cj-nyc-tickets',
      title: 'Account Executive, Season Tickets',
      club: 'New York City FC',
      city: 'New York',
      state: 'NY',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-nyc-community',
      title: 'Specialist, Community Engagement',
      club: 'New York City FC',
      city: 'New York',
      state: 'NY',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-nyc-data',
      title: 'Analyst, Fan Insights',
      club: 'New York City FC',
      city: 'New York',
      state: 'NY',
      type: 'Full-time',
      level: 'Analyst',
      category: 'Business Operations',
    },
    {
      id: 'cj-nyc-retail',
      title: 'Associate, Matchday Retail',
      club: 'New York City FC',
      city: 'New York',
      state: 'NY',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Retail',
    },
    {
      id: 'cj-nyrb-academy',
      title: 'Administrator, Red Bulls Academy',
      club: 'New York Red Bulls',
      city: 'Harrison',
      state: 'NJ',
      type: 'Full-time',
      level: 'Administrator',
      category: 'Academy',
    },
    {
      id: 'cj-nyrb-tickets',
      title: 'Manager, Group & Suite Sales',
      club: 'New York Red Bulls',
      city: 'Harrison',
      state: 'NJ',
      type: 'Full-time',
      level: 'Manager',
      category: 'Premium Sales',
    },
    {
      id: 'cj-nyrb-ops',
      title: 'Coordinator, Stadium Operations',
      club: 'New York Red Bulls',
      city: 'Harrison',
      state: 'NJ',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-nyrb-marketing',
      title: 'Specialist, Digital Marketing',
      club: 'New York Red Bulls',
      city: 'Harrison',
      state: 'NJ',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Marketing',
    },
    {
      id: 'cj-orl-security',
      title: 'Stadium Operations — Stadium Security Guard',
      club: 'Orlando City SC',
      city: 'Orlando',
      state: 'FL',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-orl-tickets',
      title: 'Account Executive, Season Ticket Sales',
      club: 'Orlando City SC',
      city: 'Orlando',
      state: 'FL',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-orl-pride',
      title: 'Coordinator, Shared Services Operations',
      club: 'Orlando City SC',
      city: 'Orlando',
      state: 'FL',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-orl-hospitality',
      title: 'Supervisor, Premium Hospitality',
      club: 'Orlando City SC',
      city: 'Orlando',
      state: 'FL',
      type: 'Full-time',
      level: 'Supervisor',
      category: 'Hospitality',
    },
    {
      id: 'cj-orl-marketing',
      title: 'Coordinator, Content Marketing',
      club: 'Orlando City SC',
      city: 'Orlando',
      state: 'FL',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Marketing',
    },
    {
      id: 'cj-phi-academy',
      title: 'Manager, YSC Academy Support',
      club: 'Philadelphia Union',
      city: 'Chester',
      state: 'PA',
      type: 'Full-time',
      level: 'Manager',
      category: 'Academy',
    },
    {
      id: 'cj-phi-tickets',
      title: 'Representative, Membership Sales',
      club: 'Philadelphia Union',
      city: 'Chester',
      state: 'PA',
      type: 'Full-time',
      level: 'Representative',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-phi-community',
      title: 'Coordinator, Union Foundation Programs',
      club: 'Philadelphia Union',
      city: 'Chester',
      state: 'PA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-phi-ops',
      title: 'Lead, Matchday Operations',
      club: 'Philadelphia Union',
      city: 'Chester',
      state: 'PA',
      type: 'Full-time',
      level: 'Lead',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-por-community',
      title: 'Manager, Community & Cascadia Relations',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      type: 'Full-time',
      level: 'Manager',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-por-tickets',
      title: 'Account Executive, Season Tickets',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-por-retail',
      title: 'Buyer, Merchandising',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      type: 'Full-time',
      level: 'Buyer',
      category: 'Retail',
    },
    {
      id: 'cj-por-ops',
      title: 'Coordinator, Providence Park Operations',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-por-marketing',
      title: 'Specialist, Brand Partnerships',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Partnerships',
    },
    {
      id: 'cj-rsl-ops',
      title: 'Manager, Stadium Operations',
      club: 'Real Salt Lake',
      city: 'Sandy',
      state: 'UT',
      type: 'Full-time',
      level: 'Manager',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-rsl-tickets',
      title: 'Account Executive, Ticket Sales',
      club: 'Real Salt Lake',
      city: 'Sandy',
      state: 'UT',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-rsl-academy',
      title: 'Coordinator, RSL Academy',
      club: 'Real Salt Lake',
      city: 'Sandy',
      state: 'UT',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Academy',
    },
    {
      id: 'cj-rsl-hr',
      title: 'Specialist, Human Resources',
      club: 'Real Salt Lake',
      city: 'Sandy',
      state: 'UT',
      type: 'Full-time',
      level: 'Specialist',
      category: 'People & Culture',
    },
    {
      id: 'cj-sdfc-launch',
      title: 'Manager, Fan Development',
      club: 'San Diego FC',
      city: 'San Diego',
      state: 'CA',
      type: 'Full-time',
      level: 'Manager',
      category: 'Marketing',
    },
    {
      id: 'cj-sdfc-tickets',
      title: 'Account Executive, Founding Memberships',
      club: 'San Diego FC',
      city: 'San Diego',
      state: 'CA',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-sdfc-partnerships',
      title: 'Coordinator, Corporate Partnerships',
      club: 'San Diego FC',
      city: 'San Diego',
      state: 'CA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Partnerships',
    },
    {
      id: 'cj-sdfc-ops',
      title: 'Supervisor, Snapdragon Matchday Ops',
      club: 'San Diego FC',
      city: 'San Diego',
      state: 'CA',
      type: 'Full-time',
      level: 'Supervisor',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-sdfc-community',
      title: 'Coordinator, Community Soccer Programs',
      club: 'San Diego FC',
      city: 'San Diego',
      state: 'CA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-sj-front-office',
      title: 'Assistant, Front Office',
      club: 'San Jose Earthquakes',
      city: 'San Jose',
      state: 'CA',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Front Office',
    },
    {
      id: 'cj-sj-ticket-sales',
      title: 'Manager, Season Ticket Sales',
      club: 'San Jose Earthquakes',
      city: 'San Jose',
      state: 'CA',
      type: 'Full-time',
      level: 'Manager',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-sj-ops',
      title: 'Coordinator, PayPal Park Operations',
      club: 'San Jose Earthquakes',
      city: 'San Jose',
      state: 'CA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-sj-marketing',
      title: 'Specialist, Digital & Social',
      club: 'San Jose Earthquakes',
      city: 'San Jose',
      state: 'CA',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Marketing',
    },
    {
      id: 'cj-sj-community',
      title: 'Coordinator, Community Relations',
      club: 'San Jose Earthquakes',
      city: 'San Jose',
      state: 'CA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-sea-guest',
      title: 'Supervisor, Guest Experience',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      type: 'Full-time',
      level: 'Supervisor',
      category: 'Guest Experience',
    },
    {
      id: 'cj-sea-tickets',
      title: 'Manager, Member Services',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      type: 'Full-time',
      level: 'Manager',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-sea-foundation',
      title: 'Coordinator, RAVE Foundation Programs',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-sea-analytics',
      title: 'Analyst, Soccer Operations Support',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      type: 'Full-time',
      level: 'Analyst',
      category: 'Business Operations',
    },
    {
      id: 'cj-sea-retail',
      title: 'Associate, Pro Shop',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Retail',
    },
    {
      id: 'cj-skc-academy',
      title: 'Coordinator, Sporting Academy',
      club: 'Sporting Kansas City',
      city: 'Kansas City',
      state: 'KS',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Academy',
    },
    {
      id: 'cj-skc-tickets',
      title: 'Account Executive, Season Tickets',
      club: 'Sporting Kansas City',
      city: 'Kansas City',
      state: 'KS',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-skc-ops',
      title: 'Manager, Children\'s Mercy Park Operations',
      club: 'Sporting Kansas City',
      city: 'Kansas City',
      state: 'KS',
      type: 'Full-time',
      level: 'Manager',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-skc-partnerships',
      title: 'Specialist, Partnership Activation',
      club: 'Sporting Kansas City',
      city: 'Kansas City',
      state: 'KS',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Partnerships',
    },
    {
      id: 'cj-stl-community',
      title: 'Manager, CITY Community Impact',
      club: 'St. Louis CITY SC',
      city: 'St. Louis',
      state: 'MO',
      type: 'Full-time',
      level: 'Manager',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-stl-tickets',
      title: 'Account Executive, Membership Sales',
      club: 'St. Louis CITY SC',
      city: 'St. Louis',
      state: 'MO',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-stl-ops',
      title: 'Coordinator, Energizer Park Operations',
      club: 'St. Louis CITY SC',
      city: 'St. Louis',
      state: 'MO',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-stl-marketing',
      title: 'Specialist, Content & Creative',
      club: 'St. Louis CITY SC',
      city: 'St. Louis',
      state: 'MO',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Marketing',
    },
    {
      id: 'cj-stl-front',
      title: 'Assistant, Front Office Administration',
      club: 'St. Louis CITY SC',
      city: 'St. Louis',
      state: 'MO',
      type: 'Part-time',
      level: 'Part Time',
      category: 'Front Office',
    },
    {
      id: 'cj-tfc-tickets',
      title: 'Manager, Ticket Sales',
      club: 'Toronto FC',
      city: 'Toronto',
      state: 'ON',
      type: 'Full-time',
      level: 'Manager',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-tfc-partnerships',
      title: 'Coordinator, Partnership Marketing',
      club: 'Toronto FC',
      city: 'Toronto',
      state: 'ON',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Partnerships',
    },
    {
      id: 'cj-tfc-academy',
      title: 'Administrator, TFC Academy',
      club: 'Toronto FC',
      city: 'Toronto',
      state: 'ON',
      type: 'Full-time',
      level: 'Administrator',
      category: 'Academy',
    },
    {
      id: 'cj-tfc-guest',
      title: 'Supervisor, BMO Field Guest Services',
      club: 'Toronto FC',
      city: 'Toronto',
      state: 'ON',
      type: 'Full-time',
      level: 'Supervisor',
      category: 'Guest Experience',
    },
    {
      id: 'cj-van-community',
      title: 'Coordinator, Whitecaps FC Community',
      club: 'Vancouver Whitecaps FC',
      city: 'Vancouver',
      state: 'BC',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Community & Foundation',
    },
    {
      id: 'cj-van-tickets',
      title: 'Account Executive, Season Tickets',
      club: 'Vancouver Whitecaps FC',
      city: 'Vancouver',
      state: 'BC',
      type: 'Full-time',
      level: 'Account Executive',
      category: 'Ticket Sales',
    },
    {
      id: 'cj-van-ops',
      title: 'Manager, BC Place Event Operations',
      club: 'Vancouver Whitecaps FC',
      city: 'Vancouver',
      state: 'BC',
      type: 'Full-time',
      level: 'Manager',
      category: 'Stadium Operations',
    },
    {
      id: 'cj-van-marketing',
      title: 'Specialist, Digital Marketing',
      club: 'Vancouver Whitecaps FC',
      city: 'Vancouver',
      state: 'BC',
      type: 'Full-time',
      level: 'Specialist',
      category: 'Marketing',
    },
    {
      id: 'cj-van-academy',
      title: 'Coordinator, Whitecaps Academy',
      club: 'Vancouver Whitecaps FC',
      city: 'Vancouver',
      state: 'BC',
      type: 'Full-time',
      level: 'Coordinator',
      category: 'Academy',
    },
  ],

  /* restore:start parked-jobs
  parkedJobs: [
    {
      id: 'job-gs-pp',
      title: 'Guest Services Associate',
      stadiumId: 'providence-park',
      category: 'Guest Services',
      type: 'Event-based',
      payMin: 18,
      payMax: 21,
      payLabel: '$18–$21 / hr',
      status: 'Open',
      deadline: '2026-08-25',
      minAge: 18,
      schedule: 'Matchdays & special events; shifts typically 5–8 hours',
      description: 'Help fans find seats, answer questions, and create a welcoming matchday experience at Providence Park.',
      responsibilities: [
        'Assist guests with seating, directions, and general inquiries',
        'Support accessible seating and guest accommodation requests',
        'Monitor aisles and report safety concerns',
        'Uphold stadium policies with a professional attitude',
      ],
      qualifications: [
        'Friendly communication skills',
        'Ability to stand for extended periods',
        'Customer service experience preferred',
      ],
      physical: 'Standing/walking for most of the shift; occasional stair climbing',
      background: 'Background check required upon offer',
      urgent: false,
    },
    {
      id: 'job-sec-bmo',
      title: 'Event Security Officer',
      stadiumId: 'bmo-stadium',
      category: 'Security',
      type: 'Part-time',
      payMin: 22,
      payMax: 26,
      payLabel: '$22–$26 / hr',
      status: 'Open',
      deadline: '2026-08-20',
      minAge: 21,
      schedule: 'Evenings & weekends; matchdays priority',
      description: 'Provide a safe environment for guests and staff during LAFC matchdays and stadium events.',
      responsibilities: [
        'Conduct bag checks and screening at entry points',
        'Monitor assigned zones and respond to incidents',
        'Support emergency procedures as directed',
        'Communicate clearly with supervisors and guests',
      ],
      qualifications: [
        'Valid security license preferred (or willingness to obtain)',
        'Prior event or security experience preferred',
        'Calm under pressure',
      ],
      physical: 'Standing, walking, occasional lifting up to 25 lbs',
      background: 'Fingerprint & background check required',
      urgent: true,
    },
    {
      id: 'job-conc-geo',
      title: 'Concessions Team Member',
      stadiumId: 'geodis-park',
      category: 'Concessions',
      type: 'Seasonal',
      payMin: 16,
      payMax: 19,
      payLabel: '$16–$19 / hr + tips',
      status: 'Open',
      deadline: '2026-09-01',
      minAge: 18,
      schedule: 'Matchdays; arrive 3 hours before kickoff',
      description: 'Serve food and beverages with speed and hospitality in GEODIS Park concession stands.',
      responsibilities: [
        'Prepare and serve menu items',
        'Handle POS transactions accurately',
        'Maintain clean service areas',
        'Follow food safety standards',
      ],
      qualifications: [
        'Food handler card preferred',
        'Cash handling experience a plus',
        'Team-oriented attitude',
      ],
      physical: 'Standing, reaching, lifting up to 30 lbs',
      background: 'Standard employment screening',
      urgent: false,
    },
    {
      id: 'job-park-lumen',
      title: 'Parking Attendant',
      stadiumId: 'lumen-field',
      category: 'Parking',
      type: 'Event-based',
      payMin: 17,
      payMax: 20,
      payLabel: '$17–$20 / hr',
      status: 'Open',
      deadline: '2026-08-22',
      minAge: 18,
      schedule: 'Matchdays; early call times for lot setup',
      description: 'Guide vehicles, manage lot flow, and assist fans arriving for Sounders matches.',
      responsibilities: [
        'Direct traffic within assigned lots',
        'Collect parking payments where applicable',
        'Support accessible parking needs',
        'Communicate lot status to supervisors',
      ],
      qualifications: [
        'Reliable attendance',
        'Comfortable working outdoors',
        'Clear verbal communication',
      ],
      physical: 'Outdoor work in varying weather; standing/walking',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-suite-pp',
      title: 'Suite Attendant',
      stadiumId: 'providence-park',
      category: 'Hospitality',
      type: 'Part-time',
      payMin: 19,
      payMax: 23,
      payLabel: '$19–$23 / hr',
      status: 'Open',
      deadline: '2026-08-28',
      minAge: 18,
      schedule: 'Matchdays & premium events',
      description: 'Deliver polished hospitality service for suite guests during Timbers matchdays.',
      responsibilities: [
        'Greet suite guests and manage suite setup',
        'Serve food and beverages',
        'Maintain suite cleanliness throughout the event',
        'Coordinate with kitchen and suite captains',
      ],
      qualifications: [
        'Hospitality or restaurant experience preferred',
        'Professional appearance and demeanor',
        'Ability to work evenings',
      ],
      physical: 'Walking, carrying trays, standing for long periods',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-usher-lumen',
      title: 'Usher / Ticket Taker',
      stadiumId: 'lumen-field',
      category: 'Guest Services',
      type: 'Event-based',
      payMin: 17,
      payMax: 19,
      payLabel: '$17–$19 / hr',
      status: 'Hiring soon',
      deadline: '2026-09-05',
      minAge: 16,
      schedule: 'Matchdays; flexible event schedule',
      description: 'Scan tickets, guide fans to seats, and keep seating bowls running smoothly.',
      responsibilities: [
        'Validate tickets at assigned gates',
        'Escort guests to correct sections',
        'Support crowd flow before and after kickoff',
        'Report issues to guest services leads',
      ],
      qualifications: [
        'Comfortable with handheld scanners',
        'Positive attitude with large crowds',
        'Weekend availability',
      ],
      physical: 'Standing and walking; stair navigation',
      background: 'Age-appropriate screening',
      urgent: false,
    },
    {
      id: 'job-retail-bmo',
      title: 'Team Store Associate',
      stadiumId: 'bmo-stadium',
      category: 'Retail',
      type: 'Part-time',
      payMin: 18,
      payMax: 20,
      payLabel: '$18–$20 / hr',
      status: 'Open',
      deadline: '2026-08-30',
      minAge: 18,
      schedule: 'Matchdays + select retail hours',
      description: 'Sell merchandise and help fans find the right gear in the BMO Stadium team store.',
      responsibilities: [
        'Provide product recommendations',
        'Process sales and returns',
        'Restock shelves during peak periods',
        'Maintain store presentation standards',
      ],
      qualifications: [
        'Retail experience preferred',
        'Basic math / POS comfort',
        'Enthusiasm for the game',
      ],
      physical: 'Standing, stocking, lifting up to 25 lbs',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-clean-geo',
      title: 'Event Clean Team',
      stadiumId: 'geodis-park',
      category: 'Operations',
      type: 'Seasonal',
      payMin: 16,
      payMax: 18,
      payLabel: '$16–$18 / hr',
      status: 'Open',
      deadline: '2026-09-10',
      minAge: 18,
      schedule: 'Pre/post match shifts; some mid-event support',
      description: 'Keep GEODIS Park clean and game-ready before, during, and after kickoff.',
      responsibilities: [
        'Clean seating areas and concourses',
        'Restock restrooms and amenities',
        'Support waste and recycling collection',
        'Follow safety and chemical handling guidelines',
      ],
      qualifications: [
        'Reliable and detail-oriented',
        'Ability to work independently',
        'Prior cleaning experience a plus',
      ],
      physical: 'Bending, lifting, walking; exposure to cleaning products',
      background: 'Standard employment screening',
      urgent: true,
    },
  ],
  restore:end parked-jobs */

  events: [
    {
      id: 'evt-pp-aug',
      title: 'Providence Park Hiring Day',
      stadiumId: 'providence-park',
      date: '2026-08-17',
      time: '10:00 AM – 3:00 PM PT',
      location: 'Providence Park — Club Level Meeting Room',
      roles: ['Guest Services', 'Suite Attendant', 'Concessions'],
      bring: ['Government-issued photo ID', 'Resume (optional)', 'List of available matchdays', 'Closed-toe shoes'],
      spots: 40,
      note: 'Ahead of Timbers vs San Diego FC (Aug 19) and Austin FC (Aug 29)',
    },
    {
      id: 'evt-bmo-aug',
      title: 'BMO Stadium Recruitment Fair',
      stadiumId: 'bmo-stadium',
      date: '2026-08-18',
      time: '11:00 AM – 4:00 PM PT',
      location: 'Exposition Park — Community Tent',
      roles: ['Security', 'Retail', 'Guest Services'],
      bring: ['Photo ID', 'Security license if applicable', 'Availability calendar'],
      spots: 60,
      note: 'Staffing for LAFC vs Portland Timbers (Aug 22) and vs New York Red Bulls (Sep 9)',
    },
    {
      id: 'evt-geo-aug',
      title: 'Nashville Matchday Crew Open House',
      stadiumId: 'geodis-park',
      date: '2026-08-20',
      time: '9:00 AM – 1:00 PM CT',
      location: 'GEODIS Park — South Plaza',
      roles: ['Concessions', 'Operations', 'Parking'],
      bring: ['Photo ID', 'Food handler card if available', 'Work eligibility documents'],
      spots: 35,
      note: 'Ahead of Nashville SC vs Columbus Crew (Aug 22) and FC Cincinnati (Aug 29)',
    },
    {
      id: 'evt-lumen-aug',
      title: 'Lumen Field Walk-Up Interviews',
      stadiumId: 'lumen-field',
      date: '2026-08-21',
      time: '12:00 PM – 5:00 PM PT',
      location: 'Lumen Field — Event Staff Office',
      roles: ['Usher', 'Parking', 'Guest Services'],
      bring: ['Photo ID', 'Resume', 'Two references'],
      spots: 50,
      note: 'Staffing for Sounders vs Chicago Fire FC (Aug 29) and later August matchdays',
    },
  ],

  courses: [
    { id: 'c1', title: 'Stadium Orientation', minutes: 25, progress: 100, category: 'Required' },
    { id: 'c2', title: 'Guest Service Basics', minutes: 30, progress: 100, category: 'Required' },
    { id: 'c3', title: 'Safety & Emergency Procedures', minutes: 40, progress: 65, category: 'Required' },
    { id: 'c4', title: 'Accessibility Awareness', minutes: 20, progress: 0, category: 'Required' },
    { id: 'c5', title: 'Role: Guest Services Deep Dive', minutes: 35, progress: 0, category: 'Role-specific' },
    { id: 'c6', title: 'Matchday Communication Radio Etiquette', minutes: 15, progress: 0, category: 'Optional' },
  ],

  applications: [
    { id: 'app1', jobId: 'job-gs-pp', status: 'Under review', updated: 'Aug 8', next: 'Recruiter screening' },
    { id: 'app2', jobId: 'job-conc-geo', status: 'Interview invited', updated: 'Aug 9', next: 'Hiring day Aug 22' },
    { id: 'app3', jobId: 'job-park-lumen', status: 'Documents needed', updated: 'Aug 7', next: 'Upload work eligibility' },
  ],

  messages: [
    { from: 'Maya R. — EventStaff Northwest', subject: 'Interview invite: Guest Services', preview: 'We loved your application. Can you join hiring day on Aug 15?', time: 'Yesterday' },
    { from: 'Jordan Lee — Music City Event Crew', subject: 'Concessions availability', preview: 'Confirm your August matchday availability when you can.', time: '2 days ago' },
  ],

  applicantsAdmin: [
    { name: 'Alex Rivera', role: 'Guest Services Associate', stadium: 'Providence Park', status: 'Review', applied: 'Aug 8' },
    { name: 'Sam Chen', role: 'Event Security Officer', stadium: 'BMO Stadium', status: 'Interview', applied: 'Aug 7' },
    { name: 'Taylor Brooks', role: 'Concessions Team Member', stadium: 'GEODIS Park', status: 'Offer', applied: 'Aug 5' },
    { name: 'Jordan Patil', role: 'Parking Attendant', stadium: 'Lumen Field', status: 'Review', applied: 'Aug 9' },
    { name: 'Casey Nguyen', role: 'Suite Attendant', stadium: 'Providence Park', status: 'Declined', applied: 'Aug 3' },
  ],
};

MW.getStadium = (id) => MW.stadiums.find((s) => s.id === id);
MW.getJob = (id) => MW.jobs.find((j) => j.id === id);
MW.getFixture = (id) => (MW.fixtures || []).find((f) => f.id === id);
MW.getMatchRole = (id) => (MW.matchRoles || []).find((r) => r.id === id);
MW.getClubJob = (id) => (MW.clubJobs || []).find((j) => j.id === id);

/** Local calendar date as YYYY-MM-DD (used to auto-hide past matchdays / deadlines). */
MW.todayISO = () => {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
};

MW.isPastDate = (iso) => Boolean(iso) && String(iso).slice(0, 10) < MW.todayISO();
MW.isUpcomingDate = (iso) => Boolean(iso) && !MW.isPastDate(iso);

MW.enrichJob = (job) => {
  const stadium = MW.getStadium(job.stadiumId);
  return { ...job, stadium };
};
MW.enrichedJobs = () =>
  MW.jobs
    .map(MW.enrichJob)
    .filter((job) => !job.deadline || MW.isUpcomingDate(job.deadline));

MW.enrichFixture = (fixture) => {
  const stadium = MW.getStadium(fixture.stadiumId);
  return { ...fixture, stadium };
};
MW.enrichedFixtures = () =>
  (MW.fixtures || [])
    .map(MW.enrichFixture)
    .filter((fx) => MW.isUpcomingDate(fx.date));

MW.upcomingEvents = () => (MW.events || []).filter((e) => MW.isUpcomingDate(e.date));

/** Home fixtures for a stadium, newest-first schedule order (upcoming only). */
MW.homeFixtures = (stadiumId) =>
  MW.enrichedFixtures()
    .filter((fx) => fx.stadiumId === stadiumId)
    .sort((a, b) => a.date.localeCompare(b.date));

MW.clubLogos = {
  'Atlanta United FC': 'assets/clubLogo/AtlantaUnitedFC.png',
  'Austin FC': 'assets/clubLogo/AustinFC.png',
  'CF Montréal': 'assets/clubLogo/CFMontr\u00e9al.png',
  'Charlotte FC': 'assets/clubLogo/CharlotteFC.png',
  'Chicago Fire FC': 'assets/clubLogo/ChicagoFireFC.png',
  'Colorado Rapids': 'assets/clubLogo/ColoradoRapids.png',
  'Columbus Crew': 'assets/clubLogo/ColumbusCrew.png',
  'D.C. United': 'assets/clubLogo/D.C.United.png',
  'FC Cincinnati': 'assets/clubLogo/FCCincinnati.png',
  'FC Dallas': 'assets/clubLogo/FCDallas.png',
  'Houston Dynamo FC': 'assets/clubLogo/HoustonDynamoFC.png',
  'Inter Miami CF': 'assets/clubLogo/InterMiamiCF.png',
  'LA Galaxy': 'assets/clubLogo/LAGalaxy.png',
  'LAFC': 'assets/clubLogo/LAFC.png',
  'Minnesota United FC': 'assets/clubLogo/MinnesotaUnitedFC.png',
  'Nashville SC': 'assets/clubLogo/NashvilleSC.png',
  'New England Revolution': 'assets/clubLogo/NewEnglandRevolution.png',
  'New York City FC': 'assets/clubLogo/NewYorkCityFC.png',
  'New York Red Bulls': 'assets/clubLogo/NewYorkRedBulls.png',
  'Orlando City SC': 'assets/clubLogo/OrlandoCitySC.png',
  'Philadelphia Union': 'assets/clubLogo/PhiladelphiaUnion.png',
  'Portland Timbers': 'assets/clubLogo/PortlandTimbers.png',
  'Real Salt Lake': 'assets/clubLogo/RealSaltLake.png',
  'San Diego FC': 'assets/clubLogo/SanDiegoFC.png',
  'San Jose Earthquakes': 'assets/clubLogo/SanJose.png',
  'Seattle Sounders FC': 'assets/clubLogo/SeattleSoundersFC.png',
  'Sporting Kansas City': 'assets/clubLogo/SportingKansasCity.png',
  'St. Louis CITY SC': 'assets/clubLogo/St.LouisCITYSC.png',
  'Toronto FC': 'assets/clubLogo/TorontoFC.png',
  'Vancouver Whitecaps FC': 'assets/clubLogo/VancouverWhitecapsFC.png',
};

MW.clubLogo = (name = '') => {
  const path = MW.clubLogos[name];
  if (!path) return '';
  return path
    .split('/')
    .map((part) => encodeURIComponent(part))
    .join('/');
};

MW.clubInitials = (name = '') =>
  name
    .replace(/FC|SC|CF|United|City|the/gi, '')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0])
    .join('')
    .toUpperCase() || 'MLS';
