/* Matchday Workforce — mock data */
const MW = {
  operator: {
    name: 'Matchday Workforce',
    legal: 'Operated by Matchday Workforce LLC — an independent stadium staffing & recruitment platform. Not affiliated with Major League Soccer or any MLS club unless listed as a partner employer.',
  },

  marketRegions: [
    {
      label: 'Pacific Northwest',
      cities: [
        { city: 'Portland', state: 'OR' },
        { city: 'Seattle', state: 'WA' },
        { city: 'Vancouver', state: 'BC' },
      ],
    },
    {
      label: 'California',
      cities: [
        { city: 'Los Angeles', state: 'CA' },
        { city: 'Carson', state: 'CA' },
        { city: 'San Diego', state: 'CA' },
        { city: 'San Jose', state: 'CA' },
      ],
    },
    {
      label: 'Mountain & Southwest',
      cities: [
        { city: 'Austin', state: 'TX' },
        { city: 'Frisco', state: 'TX' },
        { city: 'Houston', state: 'TX' },
        { city: 'Kansas City', state: 'KS' },
        { city: 'Commerce City', state: 'CO' },
        { city: 'Sandy', state: 'UT' },
      ],
    },
    {
      label: 'Southeast',
      cities: [
        { city: 'Atlanta', state: 'GA' },
        { city: 'Charlotte', state: 'NC' },
        { city: 'Orlando', state: 'FL' },
        { city: 'Miami', state: 'FL' },
        { city: 'Fort Lauderdale', state: 'FL' },
        { city: 'Nashville', state: 'TN' },
      ],
    },
    {
      label: 'Midwest',
      cities: [
        { city: 'Chicago', state: 'IL' },
        { city: 'Cincinnati', state: 'OH' },
        { city: 'Columbus', state: 'OH' },
        { city: 'St. Paul', state: 'MN' },
        { city: 'St. Louis', state: 'MO' },
      ],
    },
    {
      label: 'Northeast & Canada',
      cities: [
        { city: 'Foxborough', state: 'MA' },
        { city: 'New York', state: 'NY' },
        { city: 'Harrison', state: 'NJ' },
        { city: 'Chester', state: 'PA' },
        { city: 'Washington', state: 'DC' },
        { city: 'Toronto', state: 'ON' },
        { city: 'Montreal', state: 'QC' },
      ],
    }
  ],

  stadiums: [
    {
      id: 'mercedes-benz-stadium',
      name: 'Mercedes-Benz Stadium',
      club: 'Atlanta United FC',
      city: 'Atlanta',
      state: 'GA',
      matches: [],
    },
    {
      id: 'bank-of-america-stadium',
      name: 'Bank of America Stadium',
      club: 'Charlotte FC',
      city: 'Charlotte',
      state: 'NC',
      matches: [],
    },
    {
      id: 'interco-stadium',
      name: 'Inter&Co Stadium',
      club: 'Orlando City SC',
      city: 'Orlando',
      state: 'FL',
      matches: [],
    },
    {
      id: 'stade-saputo',
      name: 'Stade Saputo',
      club: 'CF Montréal',
      city: 'Montreal',
      state: 'QC',
      matches: [],
    },
    {
      id: 'bmo-field',
      name: 'BMO Field',
      club: 'Toronto FC',
      city: 'Toronto',
      state: 'ON',
      matches: [],
    },
    {
      id: 'shell-energy-stadium',
      name: 'Shell Energy Stadium',
      club: 'Houston Dynamo FC',
      city: 'Houston',
      state: 'TX',
      matches: [],
    },
    {
      id: 'geodis-park',
      name: 'GEODIS Park',
      club: 'Nashville SC',
      city: 'Nashville',
      state: 'TN',
      matches: [],
    },
    {
      id: 'dicks-sporting-goods-park',
      name: 'Dick\'s Sporting Goods Park',
      club: 'Colorado Rapids',
      city: 'Commerce City',
      state: 'CO',
      matches: [],
    },
    {
      id: 'america-first-field',
      name: 'America First Field',
      club: 'Real Salt Lake',
      city: 'Sandy',
      state: 'UT',
      matches: [],
    },
    {
      id: 'bmo-stadium',
      name: 'BMO Stadium',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      matches: [],
    },
    {
      id: 'paypal-park',
      name: 'PayPal Park',
      club: 'San Jose Earthquakes',
      city: 'San Jose',
      state: 'CA',
      matches: [],
    },
    {
      id: 'soldier-field',
      name: 'Soldier Field',
      club: 'Chicago Fire FC',
      city: 'Chicago',
      state: 'IL',
      matches: [],
    },
    {
      id: 'yankee-stadium',
      name: 'Yankee Stadium',
      club: 'New York City FC',
      city: 'New York',
      state: 'NY',
      matches: [],
    },
    {
      id: 'q2-stadium',
      name: 'Q2 Stadium',
      club: 'Austin FC',
      city: 'Austin',
      state: 'TX',
      matches: [],
    },
    {
      id: 'lumen-field',
      name: 'Lumen Field',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      matches: [],
    },
    {
      id: 'tql-stadium',
      name: 'TQL Stadium',
      club: 'FC Cincinnati',
      city: 'Cincinnati',
      state: 'OH',
      matches: [],
    },
    {
      id: 'audi-field',
      name: 'Audi Field',
      club: 'D.C. United',
      city: 'Washington',
      state: 'DC',
      matches: [],
    },
    {
      id: 'red-bull-arena',
      name: 'Red Bull Arena',
      club: 'New York Red Bulls',
      city: 'Harrison',
      state: 'NJ',
      matches: [],
    },
    {
      id: 'subaru-park',
      name: 'Subaru Park',
      club: 'Philadelphia Union',
      city: 'Chester',
      state: 'PA',
      matches: [],
    },
    {
      id: 'scottsmiracle-gro-field',
      name: 'ScottsMiracle-Gro Field',
      club: 'Columbus Crew',
      city: 'Columbus',
      state: 'OH',
      matches: [],
    },
    {
      id: 'childrens-mercy-park',
      name: 'Children\'s Mercy Park',
      club: 'Sporting Kansas City',
      city: 'Kansas City',
      state: 'KS',
      matches: [],
    },
    {
      id: 'allianz-field',
      name: 'Allianz Field',
      club: 'Minnesota United FC',
      city: 'St. Paul',
      state: 'MN',
      matches: [],
    },
    {
      id: 'dignity-health-sports-park',
      name: 'Dignity Health Sports Park',
      club: 'LA Galaxy',
      city: 'Carson',
      state: 'CA',
      matches: [],
    },
    {
      id: 'providence-park',
      name: 'Providence Park',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      matches: [],
    },
    {
      id: 'bc-place',
      name: 'BC Place',
      club: 'Vancouver Whitecaps FC',
      city: 'Vancouver',
      state: 'BC',
      matches: [],
    },
    {
      id: 'chase-stadium',
      name: 'Chase Stadium',
      club: 'Inter Miami CF',
      city: 'Fort Lauderdale',
      state: 'FL',
      matches: [],
    },
    {
      id: 'nu-stadium',
      name: 'Nu Stadium',
      club: 'Inter Miami CF',
      city: 'Miami',
      state: 'FL',
      matches: [],
    },
    {
      id: 'gillette-stadium',
      name: 'Gillette Stadium',
      club: 'New England Revolution',
      city: 'Foxborough',
      state: 'MA',
      matches: [],
    },
    {
      id: 'energizer-park',
      name: 'Energizer Park',
      club: 'St. Louis CITY SC',
      city: 'St. Louis',
      state: 'MO',
      matches: [],
    },
    {
      id: 'snapdragon-stadium',
      name: 'Snapdragon Stadium',
      club: 'San Diego FC',
      city: 'San Diego',
      state: 'CA',
      matches: [],
    },
    {
      id: 'toyota-stadium',
      name: 'Toyota Stadium',
      club: 'FC Dallas',
      city: 'Frisco',
      state: 'TX',
      matches: [],
    }
  ],
  jobs: [],

  /* restore:start parked-jobs
  parkedJobs: [
    {
      id: 'job-gs-pp',
      title: 'Guest Services Associate',
      stadiumId: 'providence-park',
      category: 'Guest Services',
      type: 'Event-based',
      payMin: 18,
      payMax: 21,
      payLabel: '$18–$21 / hr',
      status: 'Open',
      deadline: '2026-08-25',
      minAge: 18,
      schedule: 'Matchdays & special events; shifts typically 5–8 hours',
      description: 'Help fans find seats, answer questions, and create a welcoming matchday experience at Providence Park.',
      responsibilities: [
        'Assist guests with seating, directions, and general inquiries',
        'Support accessible seating and guest accommodation requests',
        'Monitor aisles and report safety concerns',
        'Uphold stadium policies with a professional attitude',
      ],
      qualifications: [
        'Friendly communication skills',
        'Ability to stand for extended periods',
        'Customer service experience preferred',
      ],
      physical: 'Standing/walking for most of the shift; occasional stair climbing',
      background: 'Background check required upon offer',
      urgent: false,
    },
    {
      id: 'job-sec-bmo',
      title: 'Event Security Officer',
      stadiumId: 'bmo-stadium',
      category: 'Security',
      type: 'Part-time',
      payMin: 22,
      payMax: 26,
      payLabel: '$22–$26 / hr',
      status: 'Open',
      deadline: '2026-08-20',
      minAge: 21,
      schedule: 'Evenings & weekends; matchdays priority',
      description: 'Provide a safe environment for guests and staff during LAFC matchdays and stadium events.',
      responsibilities: [
        'Conduct bag checks and screening at entry points',
        'Monitor assigned zones and respond to incidents',
        'Support emergency procedures as directed',
        'Communicate clearly with supervisors and guests',
      ],
      qualifications: [
        'Valid security license preferred (or willingness to obtain)',
        'Prior event or security experience preferred',
        'Calm under pressure',
      ],
      physical: 'Standing, walking, occasional lifting up to 25 lbs',
      background: 'Fingerprint & background check required',
      urgent: true,
    },
    {
      id: 'job-conc-geo',
      title: 'Concessions Team Member',
      stadiumId: 'geodis-park',
      category: 'Concessions',
      type: 'Seasonal',
      payMin: 16,
      payMax: 19,
      payLabel: '$16–$19 / hr + tips',
      status: 'Open',
      deadline: '2026-09-01',
      minAge: 18,
      schedule: 'Matchdays; arrive 3 hours before kickoff',
      description: 'Serve food and beverages with speed and hospitality in GEODIS Park concession stands.',
      responsibilities: [
        'Prepare and serve menu items',
        'Handle POS transactions accurately',
        'Maintain clean service areas',
        'Follow food safety standards',
      ],
      qualifications: [
        'Food handler card preferred',
        'Cash handling experience a plus',
        'Team-oriented attitude',
      ],
      physical: 'Standing, reaching, lifting up to 30 lbs',
      background: 'Standard employment screening',
      urgent: false,
    },
    {
      id: 'job-park-lumen',
      title: 'Parking Attendant',
      stadiumId: 'lumen-field',
      category: 'Parking',
      type: 'Event-based',
      payMin: 17,
      payMax: 20,
      payLabel: '$17–$20 / hr',
      status: 'Open',
      deadline: '2026-08-22',
      minAge: 18,
      schedule: 'Matchdays; early call times for lot setup',
      description: 'Guide vehicles, manage lot flow, and assist fans arriving for Sounders matches.',
      responsibilities: [
        'Direct traffic within assigned lots',
        'Collect parking payments where applicable',
        'Support accessible parking needs',
        'Communicate lot status to supervisors',
      ],
      qualifications: [
        'Reliable attendance',
        'Comfortable working outdoors',
        'Clear verbal communication',
      ],
      physical: 'Outdoor work in varying weather; standing/walking',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-suite-pp',
      title: 'Suite Attendant',
      stadiumId: 'providence-park',
      category: 'Hospitality',
      type: 'Part-time',
      payMin: 19,
      payMax: 23,
      payLabel: '$19–$23 / hr',
      status: 'Open',
      deadline: '2026-08-28',
      minAge: 18,
      schedule: 'Matchdays & premium events',
      description: 'Deliver polished hospitality service for suite guests during Timbers matchdays.',
      responsibilities: [
        'Greet suite guests and manage suite setup',
        'Serve food and beverages',
        'Maintain suite cleanliness throughout the event',
        'Coordinate with kitchen and suite captains',
      ],
      qualifications: [
        'Hospitality or restaurant experience preferred',
        'Professional appearance and demeanor',
        'Ability to work evenings',
      ],
      physical: 'Walking, carrying trays, standing for long periods',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-usher-lumen',
      title: 'Usher / Ticket Taker',
      stadiumId: 'lumen-field',
      category: 'Guest Services',
      type: 'Event-based',
      payMin: 17,
      payMax: 19,
      payLabel: '$17–$19 / hr',
      status: 'Hiring soon',
      deadline: '2026-09-05',
      minAge: 16,
      schedule: 'Matchdays; flexible event schedule',
      description: 'Scan tickets, guide fans to seats, and keep seating bowls running smoothly.',
      responsibilities: [
        'Validate tickets at assigned gates',
        'Escort guests to correct sections',
        'Support crowd flow before and after kickoff',
        'Report issues to guest services leads',
      ],
      qualifications: [
        'Comfortable with handheld scanners',
        'Positive attitude with large crowds',
        'Weekend availability',
      ],
      physical: 'Standing and walking; stair navigation',
      background: 'Age-appropriate screening',
      urgent: false,
    },
    {
      id: 'job-retail-bmo',
      title: 'Team Store Associate',
      stadiumId: 'bmo-stadium',
      category: 'Retail',
      type: 'Part-time',
      payMin: 18,
      payMax: 20,
      payLabel: '$18–$20 / hr',
      status: 'Open',
      deadline: '2026-08-30',
      minAge: 18,
      schedule: 'Matchdays + select retail hours',
      description: 'Sell merchandise and help fans find the right gear in the BMO Stadium team store.',
      responsibilities: [
        'Provide product recommendations',
        'Process sales and returns',
        'Restock shelves during peak periods',
        'Maintain store presentation standards',
      ],
      qualifications: [
        'Retail experience preferred',
        'Basic math / POS comfort',
        'Enthusiasm for the game',
      ],
      physical: 'Standing, stocking, lifting up to 25 lbs',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-clean-geo',
      title: 'Event Clean Team',
      stadiumId: 'geodis-park',
      category: 'Operations',
      type: 'Seasonal',
      payMin: 16,
      payMax: 18,
      payLabel: '$16–$18 / hr',
      status: 'Open',
      deadline: '2026-09-10',
      minAge: 18,
      schedule: 'Pre/post match shifts; some mid-event support',
      description: 'Keep GEODIS Park clean and game-ready before, during, and after kickoff.',
      responsibilities: [
        'Clean seating areas and concourses',
        'Restock restrooms and amenities',
        'Support waste and recycling collection',
        'Follow safety and chemical handling guidelines',
      ],
      qualifications: [
        'Reliable and detail-oriented',
        'Ability to work independently',
        'Prior cleaning experience a plus',
      ],
      physical: 'Bending, lifting, walking; exposure to cleaning products',
      background: 'Standard employment screening',
      urgent: true,
    },
  ],
  restore:end parked-jobs */

  events: [
    {
      id: 'evt-pp-aug',
      title: 'Providence Park Hiring Day',
      stadiumId: 'providence-park',
      date: '2026-08-14',
      time: '10:00 AM – 3:00 PM PT',
      location: 'Providence Park — Club Level Meeting Room',
      roles: ['Guest Services', 'Suite Attendant', 'Concessions'],
      bring: ['Government-issued photo ID', 'Resume (optional)', 'List of available matchdays', 'Closed-toe shoes'],
      spots: 40,
      note: 'Ahead of Timbers vs San Diego FC (Aug 19) and Austin FC (Aug 29)',
    },
    {
      id: 'evt-bmo-aug',
      title: 'BMO Stadium Recruitment Fair',
      stadiumId: 'bmo-stadium',
      date: '2026-08-13',
      time: '11:00 AM – 4:00 PM PT',
      location: 'Exposition Park — Community Tent',
      roles: ['Security', 'Retail', 'Guest Services'],
      bring: ['Photo ID', 'Security license if applicable', 'Availability calendar'],
      spots: 60,
      note: 'Staffing for LAFC vs San Diego FC (Aug 15) and vs Portland Timbers (Aug 22)',
    },
    {
      id: 'evt-geo-aug',
      title: 'Nashville Matchday Crew Open House',
      stadiumId: 'geodis-park',
      date: '2026-08-14',
      time: '9:00 AM – 1:00 PM CT',
      location: 'GEODIS Park — South Plaza',
      roles: ['Concessions', 'Operations', 'Parking'],
      bring: ['Photo ID', 'Food handler card if available', 'Work eligibility documents'],
      spots: 35,
      note: 'Ahead of Nashville SC vs Inter Miami CF (Aug 15)',
    },
    {
      id: 'evt-lumen-aug',
      title: 'Lumen Field Walk-Up Interviews',
      stadiumId: 'lumen-field',
      date: '2026-08-14',
      time: '12:00 PM – 5:00 PM PT',
      location: 'Lumen Field — Event Staff Office',
      roles: ['Usher', 'Parking', 'Guest Services'],
      bring: ['Photo ID', 'Resume', 'Two references'],
      spots: 50,
      note: 'Staffing for Sounders vs Vancouver (Aug 16) and Austin FC (Aug 19)',
    },
  ],

  courses: [
    { id: 'c1', title: 'Stadium Orientation', minutes: 25, progress: 100, category: 'Required' },
    { id: 'c2', title: 'Guest Service Basics', minutes: 30, progress: 100, category: 'Required' },
    { id: 'c3', title: 'Safety & Emergency Procedures', minutes: 40, progress: 65, category: 'Required' },
    { id: 'c4', title: 'Accessibility Awareness', minutes: 20, progress: 0, category: 'Required' },
    { id: 'c5', title: 'Role: Guest Services Deep Dive', minutes: 35, progress: 0, category: 'Role-specific' },
    { id: 'c6', title: 'Matchday Communication Radio Etiquette', minutes: 15, progress: 0, category: 'Optional' },
  ],

  applications: [
    { id: 'app1', jobId: 'job-gs-pp', status: 'Under review', updated: 'Aug 8', next: 'Recruiter screening' },
    { id: 'app2', jobId: 'job-conc-geo', status: 'Interview invited', updated: 'Aug 9', next: 'Hiring day Aug 22' },
    { id: 'app3', jobId: 'job-park-lumen', status: 'Documents needed', updated: 'Aug 7', next: 'Upload work eligibility' },
  ],

  messages: [
    { from: 'Maya R. — EventStaff Northwest', subject: 'Interview invite: Guest Services', preview: 'We loved your application. Can you join hiring day on Aug 15?', time: 'Yesterday' },
    { from: 'Jordan Lee — Music City Event Crew', subject: 'Concessions availability', preview: 'Confirm your August matchday availability when you can.', time: '2 days ago' },
  ],

  applicantsAdmin: [
    { name: 'Alex Rivera', role: 'Guest Services Associate', stadium: 'Providence Park', status: 'Review', applied: 'Aug 8' },
    { name: 'Sam Chen', role: 'Event Security Officer', stadium: 'BMO Stadium', status: 'Interview', applied: 'Aug 7' },
    { name: 'Taylor Brooks', role: 'Concessions Team Member', stadium: 'GEODIS Park', status: 'Offer', applied: 'Aug 5' },
    { name: 'Jordan Patil', role: 'Parking Attendant', stadium: 'Lumen Field', status: 'Review', applied: 'Aug 9' },
    { name: 'Casey Nguyen', role: 'Suite Attendant', stadium: 'Providence Park', status: 'Declined', applied: 'Aug 3' },
  ],
};

MW.getStadium = (id) => MW.stadiums.find((s) => s.id === id);
MW.getJob = (id) => MW.jobs.find((j) => j.id === id);
MW.enrichJob = (job) => {
  const stadium = MW.getStadium(job.stadiumId);
  return { ...job, stadium };
};
MW.enrichedJobs = () => MW.jobs.map(MW.enrichJob);
