/* Matchday Workforce — mock data */
const MW = {
  operator: {
    name: 'Matchday Workforce',
    legal: 'Operated by Matchday Workforce LLC — an independent stadium staffing & recruitment platform. Not affiliated with Major League Soccer or any MLS club unless listed as a partner employer.',
  },

  marketRegions: [
    {
      label: 'Pacific Northwest',
      cities: [
        { city: 'Portland', state: 'OR' },
        { city: 'Seattle', state: 'WA' },
        { city: 'Vancouver', state: 'BC' },
      ],
    },
    {
      label: 'California',
      cities: [
        { city: 'Los Angeles', state: 'CA' },
        { city: 'San Diego', state: 'CA' },
        { city: 'San Jose', state: 'CA' },
      ],
    },
    {
      label: 'Southwest',
      cities: [
        { city: 'Austin', state: 'TX' },
        { city: 'Dallas', state: 'TX' },
        { city: 'Houston', state: 'TX' },
        { city: 'Kansas City', state: 'MO' },
        { city: 'Salt Lake City', state: 'UT' },
      ],
    },
    {
      label: 'Southeast',
      cities: [
        { city: 'Atlanta', state: 'GA' },
        { city: 'Charlotte', state: 'NC' },
        { city: 'Miami', state: 'FL' },
        { city: 'Nashville', state: 'TN' },
        { city: 'Orlando', state: 'FL' },
      ],
    },
    {
      label: 'Midwest',
      cities: [
        { city: 'Chicago', state: 'IL' },
        { city: 'Cincinnati', state: 'OH' },
        { city: 'Columbus', state: 'OH' },
        { city: 'Minneapolis', state: 'MN' },
        { city: 'St. Louis', state: 'MO' },
      ],
    },
    {
      label: 'Northeast',
      cities: [
        { city: 'Boston', state: 'MA' },
        { city: 'New York', state: 'NY' },
        { city: 'Philadelphia', state: 'PA' },
        { city: 'Toronto', state: 'ON' },
        { city: 'Washington', state: 'DC' },
      ],
    },
  ],

  stadiums: [
    {
      id: 'providence-park',
      name: 'Providence Park',
      club: 'Portland Timbers',
      city: 'Portland',
      state: 'OR',
      capacity: '25,218',
      address: '1844 SW Morrison St, Portland, OR',
      reportTo: 'Gate D Staff Entrance — SW 18th Ave',
      partner: 'EventStaff Northwest',
      about: 'Historic downtown soccer stadium and home of the Portland Timbers. High-energy Timbers Army matchdays with full guest services, concessions, and premium operations.',
      matches: [
        { date: '2026-08-19', displayDate: 'Wed Aug 19', opponent: 'vs San Diego FC', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-08-29', displayDate: 'Sat Aug 29', opponent: 'vs Austin FC', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-09-05', displayDate: 'Sat Sep 5', opponent: 'vs Minnesota United FC', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-09-09', displayDate: 'Wed Sep 9', opponent: 'vs St. Louis CITY SC', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
      ],
      mapNote: 'Report 90 minutes before kickoff. Staff parking in Lot C with credential.',
      source: 'timbers.com 2026 schedule',
    },
    {
      id: 'bmo-stadium',
      name: 'BMO Stadium',
      club: 'LAFC',
      city: 'Los Angeles',
      state: 'CA',
      capacity: '22,000',
      address: '3939 S Figueroa St, Los Angeles, CA',
      reportTo: 'Staff Check-In — Exposition Park Gate 4',
      partner: 'Pacific Venue Services',
      about: 'Soccer-specific downtown venue in Exposition Park. Fast-paced LAFC matchdays spanning general admission, suites, retail, and security operations.',
      matches: [
        { date: '2026-08-12', displayDate: 'Wed Aug 12', opponent: 'vs Querétaro F.C.', kickoff: '7:30 PM PT', competition: 'Leagues Cup', broadcast: 'Apple TV' },
        { date: '2026-08-15', displayDate: 'Sat Aug 15', opponent: 'vs San Diego FC', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-08-22', displayDate: 'Sat Aug 22', opponent: 'vs Portland Timbers', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-09-09', displayDate: 'Wed Sep 9', opponent: 'vs New York Red Bulls', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
      ],
      mapNote: 'Credential pickup at Staff HQ tent. Uniforms distributed on first shift.',
      source: 'lafc.com / Ticketmaster 2026 home schedule',
    },
    {
      id: 'geodis-park',
      name: 'GEODIS Park',
      club: 'Nashville SC',
      city: 'Nashville',
      state: 'TN',
      capacity: '30,000',
      address: '501 Benton Ave, Nashville, TN',
      reportTo: 'Worker Entrance — Chestnut St',
      partner: 'Music City Event Crew',
      about: 'Largest soccer-specific stadium in the U.S. and home of Nashville SC. Strong matchday culture across guest services, concessions, and operations.',
      matches: [
        { date: '2026-08-15', displayDate: 'Sat Aug 15', opponent: 'vs Inter Miami CF', kickoff: '7:30 PM CT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-08-22', displayDate: 'Sat Aug 22', opponent: 'vs Columbus Crew', kickoff: '7:30 PM CT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-08-29', displayDate: 'Sat Aug 29', opponent: 'vs FC Cincinnati', kickoff: '7:30 PM CT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-09-19', displayDate: 'Sat Sep 19', opponent: 'vs Chicago Fire FC', kickoff: '8:30 PM CT', competition: 'MLS', broadcast: 'Apple TV' },
      ],
      mapNote: 'Arrive via Chestnut staff lane. Security screening required.',
      source: 'Nashville SC 2026 schedule release',
    },
    {
      id: 'lumen-field',
      name: 'Lumen Field',
      club: 'Seattle Sounders FC',
      city: 'Seattle',
      state: 'WA',
      capacity: '37,722',
      address: '800 Occidental Ave S, Seattle, WA',
      reportTo: 'South Staff Entrance — Occidental Ave S',
      partner: 'Cascade Stadium Staffing',
      about: 'Large multi-use downtown stadium and home of Sounders FC. Multi-level operations for Cascadia rivalries and regular-season matchdays.',
      matches: [
        { date: '2026-08-12', displayDate: 'Wed Aug 12', opponent: 'vs Chivas Guadalajara', kickoff: '7:30 PM PT', competition: 'Leagues Cup', broadcast: 'Apple TV' },
        { date: '2026-08-16', displayDate: 'Sun Aug 16', opponent: 'vs Vancouver Whitecaps FC', kickoff: '7:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-08-19', displayDate: 'Wed Aug 19', opponent: 'vs Austin FC', kickoff: '6:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
        { date: '2026-08-29', displayDate: 'Sat Aug 29', opponent: 'vs Chicago Fire FC', kickoff: '1:30 PM PT', competition: 'MLS', broadcast: 'Apple TV' },
      ],
      mapNote: 'Check in at South Staff desk. Bring government ID.',
      source: 'soundersfc.com single-match tickets',
    },
  ],

  jobs: [],

  /* restore:start parked-jobs
  parkedJobs: [
    {
      id: 'job-gs-pp',
      title: 'Guest Services Associate',
      stadiumId: 'providence-park',
      category: 'Guest Services',
      type: 'Event-based',
      payMin: 18,
      payMax: 21,
      payLabel: '$18–$21 / hr',
      status: 'Open',
      deadline: '2026-08-25',
      minAge: 18,
      schedule: 'Matchdays & special events; shifts typically 5–8 hours',
      description: 'Help fans find seats, answer questions, and create a welcoming matchday experience at Providence Park.',
      responsibilities: [
        'Assist guests with seating, directions, and general inquiries',
        'Support accessible seating and guest accommodation requests',
        'Monitor aisles and report safety concerns',
        'Uphold stadium policies with a professional attitude',
      ],
      qualifications: [
        'Friendly communication skills',
        'Ability to stand for extended periods',
        'Customer service experience preferred',
      ],
      physical: 'Standing/walking for most of the shift; occasional stair climbing',
      background: 'Background check required upon offer',
      urgent: false,
    },
    {
      id: 'job-sec-bmo',
      title: 'Event Security Officer',
      stadiumId: 'bmo-stadium',
      category: 'Security',
      type: 'Part-time',
      payMin: 22,
      payMax: 26,
      payLabel: '$22–$26 / hr',
      status: 'Open',
      deadline: '2026-08-20',
      minAge: 21,
      schedule: 'Evenings & weekends; matchdays priority',
      description: 'Provide a safe environment for guests and staff during LAFC matchdays and stadium events.',
      responsibilities: [
        'Conduct bag checks and screening at entry points',
        'Monitor assigned zones and respond to incidents',
        'Support emergency procedures as directed',
        'Communicate clearly with supervisors and guests',
      ],
      qualifications: [
        'Valid security license preferred (or willingness to obtain)',
        'Prior event or security experience preferred',
        'Calm under pressure',
      ],
      physical: 'Standing, walking, occasional lifting up to 25 lbs',
      background: 'Fingerprint & background check required',
      urgent: true,
    },
    {
      id: 'job-conc-geo',
      title: 'Concessions Team Member',
      stadiumId: 'geodis-park',
      category: 'Concessions',
      type: 'Seasonal',
      payMin: 16,
      payMax: 19,
      payLabel: '$16–$19 / hr + tips',
      status: 'Open',
      deadline: '2026-09-01',
      minAge: 18,
      schedule: 'Matchdays; arrive 3 hours before kickoff',
      description: 'Serve food and beverages with speed and hospitality in GEODIS Park concession stands.',
      responsibilities: [
        'Prepare and serve menu items',
        'Handle POS transactions accurately',
        'Maintain clean service areas',
        'Follow food safety standards',
      ],
      qualifications: [
        'Food handler card preferred',
        'Cash handling experience a plus',
        'Team-oriented attitude',
      ],
      physical: 'Standing, reaching, lifting up to 30 lbs',
      background: 'Standard employment screening',
      urgent: false,
    },
    {
      id: 'job-park-lumen',
      title: 'Parking Attendant',
      stadiumId: 'lumen-field',
      category: 'Parking',
      type: 'Event-based',
      payMin: 17,
      payMax: 20,
      payLabel: '$17–$20 / hr',
      status: 'Open',
      deadline: '2026-08-22',
      minAge: 18,
      schedule: 'Matchdays; early call times for lot setup',
      description: 'Guide vehicles, manage lot flow, and assist fans arriving for Sounders matches.',
      responsibilities: [
        'Direct traffic within assigned lots',
        'Collect parking payments where applicable',
        'Support accessible parking needs',
        'Communicate lot status to supervisors',
      ],
      qualifications: [
        'Reliable attendance',
        'Comfortable working outdoors',
        'Clear verbal communication',
      ],
      physical: 'Outdoor work in varying weather; standing/walking',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-suite-pp',
      title: 'Suite Attendant',
      stadiumId: 'providence-park',
      category: 'Hospitality',
      type: 'Part-time',
      payMin: 19,
      payMax: 23,
      payLabel: '$19–$23 / hr',
      status: 'Open',
      deadline: '2026-08-28',
      minAge: 18,
      schedule: 'Matchdays & premium events',
      description: 'Deliver polished hospitality service for suite guests during Timbers matchdays.',
      responsibilities: [
        'Greet suite guests and manage suite setup',
        'Serve food and beverages',
        'Maintain suite cleanliness throughout the event',
        'Coordinate with kitchen and suite captains',
      ],
      qualifications: [
        'Hospitality or restaurant experience preferred',
        'Professional appearance and demeanor',
        'Ability to work evenings',
      ],
      physical: 'Walking, carrying trays, standing for long periods',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-usher-lumen',
      title: 'Usher / Ticket Taker',
      stadiumId: 'lumen-field',
      category: 'Guest Services',
      type: 'Event-based',
      payMin: 17,
      payMax: 19,
      payLabel: '$17–$19 / hr',
      status: 'Hiring soon',
      deadline: '2026-09-05',
      minAge: 16,
      schedule: 'Matchdays; flexible event schedule',
      description: 'Scan tickets, guide fans to seats, and keep seating bowls running smoothly.',
      responsibilities: [
        'Validate tickets at assigned gates',
        'Escort guests to correct sections',
        'Support crowd flow before and after kickoff',
        'Report issues to guest services leads',
      ],
      qualifications: [
        'Comfortable with handheld scanners',
        'Positive attitude with large crowds',
        'Weekend availability',
      ],
      physical: 'Standing and walking; stair navigation',
      background: 'Age-appropriate screening',
      urgent: false,
    },
    {
      id: 'job-retail-bmo',
      title: 'Team Store Associate',
      stadiumId: 'bmo-stadium',
      category: 'Retail',
      type: 'Part-time',
      payMin: 18,
      payMax: 20,
      payLabel: '$18–$20 / hr',
      status: 'Open',
      deadline: '2026-08-30',
      minAge: 18,
      schedule: 'Matchdays + select retail hours',
      description: 'Sell merchandise and help fans find the right gear in the BMO Stadium team store.',
      responsibilities: [
        'Provide product recommendations',
        'Process sales and returns',
        'Restock shelves during peak periods',
        'Maintain store presentation standards',
      ],
      qualifications: [
        'Retail experience preferred',
        'Basic math / POS comfort',
        'Enthusiasm for the game',
      ],
      physical: 'Standing, stocking, lifting up to 25 lbs',
      background: 'Background check required',
      urgent: false,
    },
    {
      id: 'job-clean-geo',
      title: 'Event Clean Team',
      stadiumId: 'geodis-park',
      category: 'Operations',
      type: 'Seasonal',
      payMin: 16,
      payMax: 18,
      payLabel: '$16–$18 / hr',
      status: 'Open',
      deadline: '2026-09-10',
      minAge: 18,
      schedule: 'Pre/post match shifts; some mid-event support',
      description: 'Keep GEODIS Park clean and game-ready before, during, and after kickoff.',
      responsibilities: [
        'Clean seating areas and concourses',
        'Restock restrooms and amenities',
        'Support waste and recycling collection',
        'Follow safety and chemical handling guidelines',
      ],
      qualifications: [
        'Reliable and detail-oriented',
        'Ability to work independently',
        'Prior cleaning experience a plus',
      ],
      physical: 'Bending, lifting, walking; exposure to cleaning products',
      background: 'Standard employment screening',
      urgent: true,
    },
  ],
  restore:end parked-jobs */

  events: [
    {
      id: 'evt-pp-aug',
      title: 'Providence Park Hiring Day',
      stadiumId: 'providence-park',
      date: '2026-08-14',
      time: '10:00 AM – 3:00 PM PT',
      location: 'Providence Park — Club Level Meeting Room',
      roles: ['Guest Services', 'Suite Attendant', 'Concessions'],
      bring: ['Government-issued photo ID', 'Resume (optional)', 'List of available matchdays', 'Closed-toe shoes'],
      spots: 40,
      note: 'Ahead of Timbers vs San Diego FC (Aug 19) and Austin FC (Aug 29)',
    },
    {
      id: 'evt-bmo-aug',
      title: 'BMO Stadium Recruitment Fair',
      stadiumId: 'bmo-stadium',
      date: '2026-08-13',
      time: '11:00 AM – 4:00 PM PT',
      location: 'Exposition Park — Community Tent',
      roles: ['Security', 'Retail', 'Guest Services'],
      bring: ['Photo ID', 'Security license if applicable', 'Availability calendar'],
      spots: 60,
      note: 'Staffing for LAFC vs San Diego FC (Aug 15) and vs Portland Timbers (Aug 22)',
    },
    {
      id: 'evt-geo-aug',
      title: 'Nashville Matchday Crew Open House',
      stadiumId: 'geodis-park',
      date: '2026-08-14',
      time: '9:00 AM – 1:00 PM CT',
      location: 'GEODIS Park — South Plaza',
      roles: ['Concessions', 'Operations', 'Parking'],
      bring: ['Photo ID', 'Food handler card if available', 'Work eligibility documents'],
      spots: 35,
      note: 'Ahead of Nashville SC vs Inter Miami CF (Aug 15)',
    },
    {
      id: 'evt-lumen-aug',
      title: 'Lumen Field Walk-Up Interviews',
      stadiumId: 'lumen-field',
      date: '2026-08-14',
      time: '12:00 PM – 5:00 PM PT',
      location: 'Lumen Field — Event Staff Office',
      roles: ['Usher', 'Parking', 'Guest Services'],
      bring: ['Photo ID', 'Resume', 'Two references'],
      spots: 50,
      note: 'Staffing for Sounders vs Vancouver (Aug 16) and Austin FC (Aug 19)',
    },
  ],

  courses: [
    { id: 'c1', title: 'Stadium Orientation', minutes: 25, progress: 100, category: 'Required' },
    { id: 'c2', title: 'Guest Service Basics', minutes: 30, progress: 100, category: 'Required' },
    { id: 'c3', title: 'Safety & Emergency Procedures', minutes: 40, progress: 65, category: 'Required' },
    { id: 'c4', title: 'Accessibility Awareness', minutes: 20, progress: 0, category: 'Required' },
    { id: 'c5', title: 'Role: Guest Services Deep Dive', minutes: 35, progress: 0, category: 'Role-specific' },
    { id: 'c6', title: 'Matchday Communication Radio Etiquette', minutes: 15, progress: 0, category: 'Optional' },
  ],

  applications: [
    { id: 'app1', jobId: 'job-gs-pp', status: 'Under review', updated: 'Aug 8', next: 'Recruiter screening' },
    { id: 'app2', jobId: 'job-conc-geo', status: 'Interview invited', updated: 'Aug 9', next: 'Hiring day Aug 22' },
    { id: 'app3', jobId: 'job-park-lumen', status: 'Documents needed', updated: 'Aug 7', next: 'Upload work eligibility' },
  ],

  messages: [
    { from: 'Maya R. — EventStaff Northwest', subject: 'Interview invite: Guest Services', preview: 'We loved your application. Can you join hiring day on Aug 15?', time: 'Yesterday' },
    { from: 'Jordan Lee — Music City Event Crew', subject: 'Concessions availability', preview: 'Confirm your August matchday availability when you can.', time: '2 days ago' },
  ],

  applicantsAdmin: [
    { name: 'Alex Rivera', role: 'Guest Services Associate', stadium: 'Providence Park', status: 'Review', applied: 'Aug 8' },
    { name: 'Sam Chen', role: 'Event Security Officer', stadium: 'BMO Stadium', status: 'Interview', applied: 'Aug 7' },
    { name: 'Taylor Brooks', role: 'Concessions Team Member', stadium: 'GEODIS Park', status: 'Offer', applied: 'Aug 5' },
    { name: 'Jordan Patil', role: 'Parking Attendant', stadium: 'Lumen Field', status: 'Review', applied: 'Aug 9' },
    { name: 'Casey Nguyen', role: 'Suite Attendant', stadium: 'Providence Park', status: 'Declined', applied: 'Aug 3' },
  ],
};

MW.getStadium = (id) => MW.stadiums.find((s) => s.id === id);
MW.getJob = (id) => MW.jobs.find((j) => j.id === id);
MW.enrichJob = (job) => {
  const stadium = MW.getStadium(job.stadiumId);
  return { ...job, stadium };
};
MW.enrichedJobs = () => MW.jobs.map(MW.enrichJob);
