/* MLS matchday fixtures — Aug–Oct 2026 */
MW.fixtures = [
  {
    id: 'm-2026-08-15-atlanta-united-fc-new-york-red-bulls',
    date: '2026-08-15',
    time: '7:30 PM ET',
    home: 'Atlanta United FC',
    away: 'New York Red Bulls',
    stadiumId: 'mercedes-benz-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-08-15-charlotte-fc-columbus-crew',
    date: '2026-08-15',
    time: '7:30 PM ET',
    home: 'Charlotte FC',
    away: 'Columbus Crew',
    stadiumId: 'bank-of-america-stadium',
    openings: 11,
  },
  {
    id: 'm-2026-08-15-orlando-city-sc-fc-cincinnati',
    date: '2026-08-15',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'FC Cincinnati',
    stadiumId: 'interco-stadium',
    openings: 14,
  },
  {
    id: 'm-2026-08-15-cf-montréal-dc-united',
    date: '2026-08-15',
    time: '7:30 PM ET',
    home: 'CF Montréal',
    away: 'D.C. United',
    stadiumId: 'stade-saputo',
    openings: 17,
  },
  {
    id: 'm-2026-08-15-toronto-fc-new-england-revolu',
    date: '2026-08-15',
    time: '7:30 PM ET',
    home: 'Toronto FC',
    away: 'New England Revolution',
    stadiumId: 'bmo-field',
    openings: 20,
  },
  {
    id: 'm-2026-08-15-houston-dynamo-fc-la-galaxy',
    date: '2026-08-15',
    time: '7:30 PM CT',
    home: 'Houston Dynamo FC',
    away: 'LA Galaxy',
    stadiumId: 'shell-energy-stadium',
    openings: 23,
  },
  {
    id: 'm-2026-08-15-nashville-sc-inter-miami-cf',
    date: '2026-08-15',
    time: '7:30 PM CT',
    home: 'Nashville SC',
    away: 'Inter Miami CF',
    stadiumId: 'geodis-park',
    openings: 9,
  },
  {
    id: 'm-2026-08-15-colorado-rapids-sporting-kansas-ci',
    date: '2026-08-15',
    time: '7:30 PM MT',
    home: 'Colorado Rapids',
    away: 'Sporting Kansas City',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 12,
  },
  {
    id: 'm-2026-08-15-real-salt-lake-minnesota-united-f',
    date: '2026-08-15',
    time: '7:30 PM MT',
    home: 'Real Salt Lake',
    away: 'Minnesota United FC',
    stadiumId: 'america-first-field',
    openings: 15,
  },
  {
    id: 'm-2026-08-15-lafc-san-diego-fc',
    date: '2026-08-15',
    time: '7:30 PM PT',
    home: 'LAFC',
    away: 'San Diego FC',
    stadiumId: 'bmo-stadium',
    openings: 18,
  },
  {
    id: 'm-2026-08-15-san-jose-earthquak-st-louis-city-sc',
    date: '2026-08-15',
    time: '7:30 PM PT',
    home: 'San Jose Earthquakes',
    away: 'St. Louis CITY SC',
    stadiumId: 'paypal-park',
    openings: 21,
  },
  {
    id: 'm-2026-08-16-chicago-fire-fc-portland-timbers',
    date: '2026-08-16',
    time: '5:00 PM CT',
    home: 'Chicago Fire FC',
    away: 'Portland Timbers',
    stadiumId: 'soldier-field',
    openings: 24,
  },
  {
    id: 'm-2026-08-16-new-york-city-fc-philadelphia-union',
    date: '2026-08-16',
    time: '6:00 PM ET',
    home: 'New York City FC',
    away: 'Philadelphia Union',
    stadiumId: 'yankee-stadium',
    openings: 10,
  },
  {
    id: 'm-2026-08-16-austin-fc-fc-dallas',
    date: '2026-08-16',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'FC Dallas',
    stadiumId: 'q2-stadium',
    openings: 13,
  },
  {
    id: 'm-2026-08-16-seattle-sounders-f-vancouver-whitecap',
    date: '2026-08-16',
    time: '7:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'lumen-field',
    openings: 16,
  },
  {
    id: 'm-2026-08-19-fc-cincinnati-new-york-city-fc',
    date: '2026-08-19',
    time: '7:30 PM ET',
    home: 'FC Cincinnati',
    away: 'New York City FC',
    stadiumId: 'tql-stadium',
    openings: 19,
  },
  {
    id: 'm-2026-08-19-dc-united-new-england-revolu',
    date: '2026-08-19',
    time: '7:30 PM ET',
    home: 'D.C. United',
    away: 'New England Revolution',
    stadiumId: 'audi-field',
    openings: 22,
  },
  {
    id: 'm-2026-08-19-new-york-red-bulls-nashville-sc',
    date: '2026-08-19',
    time: '7:30 PM ET',
    home: 'New York Red Bulls',
    away: 'Nashville SC',
    stadiumId: 'red-bull-arena',
    openings: 8,
  },
  {
    id: 'm-2026-08-19-orlando-city-sc-chicago-fire-fc',
    date: '2026-08-19',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'Chicago Fire FC',
    stadiumId: 'interco-stadium',
    openings: 11,
  },
  {
    id: 'm-2026-08-19-philadelphia-union-inter-miami-cf',
    date: '2026-08-19',
    time: '7:30 PM ET',
    home: 'Philadelphia Union',
    away: 'Inter Miami CF',
    stadiumId: 'subaru-park',
    openings: 14,
  },
  {
    id: 'm-2026-08-19-columbus-crew-cf-montréal',
    date: '2026-08-19',
    time: '7:30 PM ET',
    home: 'Columbus Crew',
    away: 'CF Montréal',
    stadiumId: 'scottsmiracle-gro-field',
    openings: 17,
  },
  {
    id: 'm-2026-08-19-toronto-fc-charlotte-fc',
    date: '2026-08-19',
    time: '7:30 PM ET',
    home: 'Toronto FC',
    away: 'Charlotte FC',
    stadiumId: 'bmo-field',
    openings: 20,
  },
  {
    id: 'm-2026-08-19-sporting-kansas-ci-st-louis-city-sc',
    date: '2026-08-19',
    time: '7:00 PM CT',
    home: 'Sporting Kansas City',
    away: 'St. Louis CITY SC',
    stadiumId: 'childrens-mercy-park',
    openings: 23,
  },
  {
    id: 'm-2026-08-19-minnesota-united-f-atlanta-united-fc',
    date: '2026-08-19',
    time: '7:30 PM CT',
    home: 'Minnesota United FC',
    away: 'Atlanta United FC',
    stadiumId: 'allianz-field',
    openings: 9,
  },
  {
    id: 'm-2026-08-19-colorado-rapids-lafc',
    date: '2026-08-19',
    time: '7:30 PM MT',
    home: 'Colorado Rapids',
    away: 'LAFC',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 12,
  },
  {
    id: 'm-2026-08-19-real-salt-lake-fc-dallas',
    date: '2026-08-19',
    time: '7:30 PM MT',
    home: 'Real Salt Lake',
    away: 'FC Dallas',
    stadiumId: 'america-first-field',
    openings: 15,
  },
  {
    id: 'm-2026-08-19-seattle-sounders-f-austin-fc',
    date: '2026-08-19',
    time: '6:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'Austin FC',
    stadiumId: 'lumen-field',
    openings: 18,
  },
  {
    id: 'm-2026-08-19-la-galaxy-san-jose-earthquak',
    date: '2026-08-19',
    time: '7:30 PM PT',
    home: 'LA Galaxy',
    away: 'San Jose Earthquakes',
    stadiumId: 'dignity-health-sports-park',
    openings: 21,
  },
  {
    id: 'm-2026-08-19-portland-timbers-san-diego-fc',
    date: '2026-08-19',
    time: '7:30 PM PT',
    home: 'Portland Timbers',
    away: 'San Diego FC',
    stadiumId: 'providence-park',
    openings: 24,
  },
  {
    id: 'm-2026-08-19-vancouver-whitecap-houston-dynamo-fc',
    date: '2026-08-19',
    time: '7:30 PM PT',
    home: 'Vancouver Whitecaps FC',
    away: 'Houston Dynamo FC',
    stadiumId: 'bc-place',
    openings: 10,
  },
  {
    id: 'm-2026-08-22-charlotte-fc-dc-united',
    date: '2026-08-22',
    time: '7:30 PM ET',
    home: 'Charlotte FC',
    away: 'D.C. United',
    stadiumId: 'bank-of-america-stadium',
    openings: 13,
  },
  {
    id: 'm-2026-08-22-fc-cincinnati-seattle-sounders-f',
    date: '2026-08-22',
    time: '7:30 PM ET',
    home: 'FC Cincinnati',
    away: 'Seattle Sounders FC',
    stadiumId: 'tql-stadium',
    openings: 16,
  },
  {
    id: 'm-2026-08-22-new-york-red-bulls-chicago-fire-fc',
    date: '2026-08-22',
    time: '7:30 PM ET',
    home: 'New York Red Bulls',
    away: 'Chicago Fire FC',
    stadiumId: 'red-bull-arena',
    openings: 19,
  },
  {
    id: 'm-2026-08-22-orlando-city-sc-real-salt-lake',
    date: '2026-08-22',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'Real Salt Lake',
    stadiumId: 'interco-stadium',
    openings: 22,
  },
  {
    id: 'm-2026-08-22-inter-miami-cf-toronto-fc',
    date: '2026-08-22',
    time: '7:30 PM ET',
    home: 'Inter Miami CF',
    away: 'Toronto FC',
    stadiumId: 'chase-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-08-22-cf-montréal-la-galaxy',
    date: '2026-08-22',
    time: '7:30 PM ET',
    home: 'CF Montréal',
    away: 'LA Galaxy',
    stadiumId: 'stade-saputo',
    openings: 11,
  },
  {
    id: 'm-2026-08-22-austin-fc-philadelphia-union',
    date: '2026-08-22',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'Philadelphia Union',
    stadiumId: 'q2-stadium',
    openings: 14,
  },
  {
    id: 'm-2026-08-22-nashville-sc-columbus-crew',
    date: '2026-08-22',
    time: '7:30 PM CT',
    home: 'Nashville SC',
    away: 'Columbus Crew',
    stadiumId: 'geodis-park',
    openings: 17,
  },
  {
    id: 'm-2026-08-22-st-louis-city-sc-houston-dynamo-fc',
    date: '2026-08-22',
    time: '7:30 PM CT',
    home: 'St. Louis CITY SC',
    away: 'Houston Dynamo FC',
    stadiumId: 'energizer-park',
    openings: 20,
  },
  {
    id: 'm-2026-08-22-vancouver-whitecap-fc-dallas',
    date: '2026-08-22',
    time: '6:30 PM PT',
    home: 'Vancouver Whitecaps FC',
    away: 'FC Dallas',
    stadiumId: 'bc-place',
    openings: 23,
  },
  {
    id: 'm-2026-08-22-lafc-portland-timbers',
    date: '2026-08-22',
    time: '7:30 PM PT',
    home: 'LAFC',
    away: 'Portland Timbers',
    stadiumId: 'bmo-stadium',
    openings: 9,
  },
  {
    id: 'm-2026-08-22-san-diego-fc-colorado-rapids',
    date: '2026-08-22',
    time: '7:30 PM PT',
    home: 'San Diego FC',
    away: 'Colorado Rapids',
    stadiumId: 'snapdragon-stadium',
    openings: 12,
  },
  {
    id: 'm-2026-08-22-san-jose-earthquak-minnesota-united-f',
    date: '2026-08-22',
    time: '7:30 PM PT',
    home: 'San Jose Earthquakes',
    away: 'Minnesota United FC',
    stadiumId: 'paypal-park',
    openings: 15,
  },
  {
    id: 'm-2026-08-23-new-england-revolu-new-york-city-fc',
    date: '2026-08-23',
    time: '4:30 PM ET',
    home: 'New England Revolution',
    away: 'New York City FC',
    stadiumId: 'gillette-stadium',
    openings: 18,
  },
  {
    id: 'm-2026-08-23-atlanta-united-fc-sporting-kansas-ci',
    date: '2026-08-23',
    time: '7:00 PM ET',
    home: 'Atlanta United FC',
    away: 'Sporting Kansas City',
    stadiumId: 'mercedes-benz-stadium',
    openings: 21,
  },
  {
    id: 'm-2026-08-29-seattle-sounders-f-chicago-fire-fc',
    date: '2026-08-29',
    time: '1:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'Chicago Fire FC',
    stadiumId: 'lumen-field',
    openings: 24,
  },
  {
    id: 'm-2026-08-29-atlanta-united-fc-charlotte-fc',
    date: '2026-08-29',
    time: '7:30 PM ET',
    home: 'Atlanta United FC',
    away: 'Charlotte FC',
    stadiumId: 'mercedes-benz-stadium',
    openings: 10,
  },
  {
    id: 'm-2026-08-29-columbus-crew-new-england-revolu',
    date: '2026-08-29',
    time: '7:30 PM ET',
    home: 'Columbus Crew',
    away: 'New England Revolution',
    stadiumId: 'scottsmiracle-gro-field',
    openings: 13,
  },
  {
    id: 'm-2026-08-29-dc-united-lafc',
    date: '2026-08-29',
    time: '7:30 PM ET',
    home: 'D.C. United',
    away: 'LAFC',
    stadiumId: 'audi-field',
    openings: 16,
  },
  {
    id: 'm-2026-08-29-new-york-red-bulls-philadelphia-union',
    date: '2026-08-29',
    time: '7:30 PM ET',
    home: 'New York Red Bulls',
    away: 'Philadelphia Union',
    stadiumId: 'red-bull-arena',
    openings: 19,
  },
  {
    id: 'm-2026-08-29-inter-miami-cf-cf-montréal',
    date: '2026-08-29',
    time: '7:30 PM ET',
    home: 'Inter Miami CF',
    away: 'CF Montréal',
    stadiumId: 'chase-stadium',
    openings: 22,
  },
  {
    id: 'm-2026-08-29-toronto-fc-new-york-city-fc',
    date: '2026-08-29',
    time: '7:30 PM ET',
    home: 'Toronto FC',
    away: 'New York City FC',
    stadiumId: 'bmo-field',
    openings: 8,
  },
  {
    id: 'm-2026-08-29-houston-dynamo-fc-san-jose-earthquak',
    date: '2026-08-29',
    time: '7:30 PM CT',
    home: 'Houston Dynamo FC',
    away: 'San Jose Earthquakes',
    stadiumId: 'shell-energy-stadium',
    openings: 11,
  },
  {
    id: 'm-2026-08-29-minnesota-united-f-orlando-city-sc',
    date: '2026-08-29',
    time: '7:30 PM CT',
    home: 'Minnesota United FC',
    away: 'Orlando City SC',
    stadiumId: 'allianz-field',
    openings: 14,
  },
  {
    id: 'm-2026-08-29-nashville-sc-fc-cincinnati',
    date: '2026-08-29',
    time: '7:30 PM CT',
    home: 'Nashville SC',
    away: 'FC Cincinnati',
    stadiumId: 'geodis-park',
    openings: 17,
  },
  {
    id: 'm-2026-08-29-sporting-kansas-ci-vancouver-whitecap',
    date: '2026-08-29',
    time: '7:30 PM CT',
    home: 'Sporting Kansas City',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'childrens-mercy-park',
    openings: 20,
  },
  {
    id: 'm-2026-08-29-colorado-rapids-real-salt-lake',
    date: '2026-08-29',
    time: '7:30 PM MT',
    home: 'Colorado Rapids',
    away: 'Real Salt Lake',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 23,
  },
  {
    id: 'm-2026-08-29-portland-timbers-austin-fc',
    date: '2026-08-29',
    time: '7:30 PM PT',
    home: 'Portland Timbers',
    away: 'Austin FC',
    stadiumId: 'providence-park',
    openings: 9,
  },
  {
    id: 'm-2026-08-29-san-diego-fc-la-galaxy',
    date: '2026-08-29',
    time: '7:30 PM PT',
    home: 'San Diego FC',
    away: 'LA Galaxy',
    stadiumId: 'snapdragon-stadium',
    openings: 12,
  },
  {
    id: 'm-2026-08-30-st-louis-city-sc-fc-dallas',
    date: '2026-08-30',
    time: '6:00 PM CT',
    home: 'St. Louis CITY SC',
    away: 'FC Dallas',
    stadiumId: 'energizer-park',
    openings: 15,
  },
  {
    id: 'm-2026-09-05-orlando-city-sc-san-diego-fc',
    date: '2026-09-05',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'San Diego FC',
    stadiumId: 'interco-stadium',
    openings: 18,
  },
  {
    id: 'm-2026-09-05-philadelphia-union-cf-montréal',
    date: '2026-09-05',
    time: '7:30 PM ET',
    home: 'Philadelphia Union',
    away: 'CF Montréal',
    stadiumId: 'subaru-park',
    openings: 21,
  },
  {
    id: 'm-2026-09-05-fc-cincinnati-dc-united',
    date: '2026-09-05',
    time: '7:30 PM ET',
    home: 'FC Cincinnati',
    away: 'D.C. United',
    stadiumId: 'tql-stadium',
    openings: 24,
  },
  {
    id: 'm-2026-09-05-charlotte-fc-houston-dynamo-fc',
    date: '2026-09-05',
    time: '7:30 PM ET',
    home: 'Charlotte FC',
    away: 'Houston Dynamo FC',
    stadiumId: 'bank-of-america-stadium',
    openings: 10,
  },
  {
    id: 'm-2026-09-05-columbus-crew-colorado-rapids',
    date: '2026-09-05',
    time: '7:30 PM ET',
    home: 'Columbus Crew',
    away: 'Colorado Rapids',
    stadiumId: 'scottsmiracle-gro-field',
    openings: 13,
  },
  {
    id: 'm-2026-09-05-toronto-fc-chicago-fire-fc',
    date: '2026-09-05',
    time: '7:30 PM ET',
    home: 'Toronto FC',
    away: 'Chicago Fire FC',
    stadiumId: 'bmo-field',
    openings: 16,
  },
  {
    id: 'm-2026-09-05-inter-miami-cf-atlanta-united-fc',
    date: '2026-09-05',
    time: '7:30 PM ET',
    home: 'Inter Miami CF',
    away: 'Atlanta United FC',
    stadiumId: 'nu-stadium',
    openings: 19,
  },
  {
    id: 'm-2026-09-05-austin-fc-san-jose-earthquak',
    date: '2026-09-05',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'San Jose Earthquakes',
    stadiumId: 'q2-stadium',
    openings: 22,
  },
  {
    id: 'm-2026-09-05-fc-dallas-sporting-kansas-ci',
    date: '2026-09-05',
    time: '7:30 PM CT',
    home: 'FC Dallas',
    away: 'Sporting Kansas City',
    stadiumId: 'toyota-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-09-05-seattle-sounders-f-new-york-red-bulls',
    date: '2026-09-05',
    time: '5:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'New York Red Bulls',
    stadiumId: 'lumen-field',
    openings: 11,
  },
  {
    id: 'm-2026-09-05-la-galaxy-new-england-revolu',
    date: '2026-09-05',
    time: '6:30 PM PT',
    home: 'LA Galaxy',
    away: 'New England Revolution',
    stadiumId: 'dignity-health-sports-park',
    openings: 14,
  },
  {
    id: 'm-2026-09-05-real-salt-lake-lafc',
    date: '2026-09-05',
    time: '7:30 PM MT',
    home: 'Real Salt Lake',
    away: 'LAFC',
    stadiumId: 'america-first-field',
    openings: 17,
  },
  {
    id: 'm-2026-09-05-portland-timbers-minnesota-united-f',
    date: '2026-09-05',
    time: '7:30 PM PT',
    home: 'Portland Timbers',
    away: 'Minnesota United FC',
    stadiumId: 'providence-park',
    openings: 20,
  },
  {
    id: 'm-2026-09-05-vancouver-whitecap-st-louis-city-sc',
    date: '2026-09-05',
    time: '7:30 PM PT',
    home: 'Vancouver Whitecaps FC',
    away: 'St. Louis CITY SC',
    stadiumId: 'bc-place',
    openings: 23,
  },
  {
    id: 'm-2026-09-09-cf-montréal-charlotte-fc',
    date: '2026-09-09',
    time: '7:30 PM ET',
    home: 'CF Montréal',
    away: 'Charlotte FC',
    stadiumId: 'stade-saputo',
    openings: 9,
  },
  {
    id: 'm-2026-09-09-philadelphia-union-fc-cincinnati',
    date: '2026-09-09',
    time: '7:30 PM ET',
    home: 'Philadelphia Union',
    away: 'FC Cincinnati',
    stadiumId: 'subaru-park',
    openings: 12,
  },
  {
    id: 'm-2026-09-09-atlanta-united-fc-orlando-city-sc',
    date: '2026-09-09',
    time: '7:30 PM ET',
    home: 'Atlanta United FC',
    away: 'Orlando City SC',
    stadiumId: 'mercedes-benz-stadium',
    openings: 15,
  },
  {
    id: 'm-2026-09-09-new-york-city-fc-new-england-revolu',
    date: '2026-09-09',
    time: '7:30 PM ET',
    home: 'New York City FC',
    away: 'New England Revolution',
    stadiumId: 'yankee-stadium',
    openings: 18,
  },
  {
    id: 'm-2026-09-09-dc-united-columbus-crew',
    date: '2026-09-09',
    time: '7:30 PM ET',
    home: 'D.C. United',
    away: 'Columbus Crew',
    stadiumId: 'audi-field',
    openings: 21,
  },
  {
    id: 'm-2026-09-09-toronto-fc-nashville-sc',
    date: '2026-09-09',
    time: '7:30 PM ET',
    home: 'Toronto FC',
    away: 'Nashville SC',
    stadiumId: 'bmo-field',
    openings: 24,
  },
  {
    id: 'm-2026-09-09-houston-dynamo-fc-real-salt-lake',
    date: '2026-09-09',
    time: '7:30 PM CT',
    home: 'Houston Dynamo FC',
    away: 'Real Salt Lake',
    stadiumId: 'shell-energy-stadium',
    openings: 10,
  },
  {
    id: 'm-2026-09-09-chicago-fire-fc-inter-miami-cf',
    date: '2026-09-09',
    time: '7:30 PM CT',
    home: 'Chicago Fire FC',
    away: 'Inter Miami CF',
    stadiumId: 'soldier-field',
    openings: 13,
  },
  {
    id: 'm-2026-09-09-minnesota-united-f-fc-dallas',
    date: '2026-09-09',
    time: '7:30 PM CT',
    home: 'Minnesota United FC',
    away: 'FC Dallas',
    stadiumId: 'allianz-field',
    openings: 16,
  },
  {
    id: 'm-2026-09-09-austin-fc-colorado-rapids',
    date: '2026-09-09',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'Colorado Rapids',
    stadiumId: 'q2-stadium',
    openings: 19,
  },
  {
    id: 'm-2026-09-09-lafc-new-york-red-bulls',
    date: '2026-09-09',
    time: '7:30 PM PT',
    home: 'LAFC',
    away: 'New York Red Bulls',
    stadiumId: 'bmo-stadium',
    openings: 22,
  },
  {
    id: 'm-2026-09-09-portland-timbers-st-louis-city-sc',
    date: '2026-09-09',
    time: '7:30 PM PT',
    home: 'Portland Timbers',
    away: 'St. Louis CITY SC',
    stadiumId: 'providence-park',
    openings: 8,
  },
  {
    id: 'm-2026-09-09-san-diego-fc-san-jose-earthquak',
    date: '2026-09-09',
    time: '7:30 PM PT',
    home: 'San Diego FC',
    away: 'San Jose Earthquakes',
    stadiumId: 'snapdragon-stadium',
    openings: 11,
  },
  {
    id: 'm-2026-09-09-vancouver-whitecap-la-galaxy',
    date: '2026-09-09',
    time: '7:30 PM PT',
    home: 'Vancouver Whitecaps FC',
    away: 'LA Galaxy',
    stadiumId: 'bc-place',
    openings: 14,
  },
  {
    id: 'm-2026-09-12-inter-miami-cf-nashville-sc',
    date: '2026-09-12',
    time: '7:30 PM ET',
    home: 'Inter Miami CF',
    away: 'Nashville SC',
    stadiumId: 'nu-stadium',
    openings: 17,
  },
  {
    id: 'm-2026-09-12-orlando-city-sc-toronto-fc',
    date: '2026-09-12',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'Toronto FC',
    stadiumId: 'interco-stadium',
    openings: 20,
  },
  {
    id: 'm-2026-09-12-fc-cincinnati-charlotte-fc',
    date: '2026-09-12',
    time: '7:30 PM ET',
    home: 'FC Cincinnati',
    away: 'Charlotte FC',
    stadiumId: 'tql-stadium',
    openings: 23,
  },
  {
    id: 'm-2026-09-12-dc-united-atlanta-united-fc',
    date: '2026-09-12',
    time: '7:30 PM ET',
    home: 'D.C. United',
    away: 'Atlanta United FC',
    stadiumId: 'audi-field',
    openings: 9,
  },
  {
    id: 'm-2026-09-12-columbus-crew-new-york-red-bulls',
    date: '2026-09-12',
    time: '7:30 PM ET',
    home: 'Columbus Crew',
    away: 'New York Red Bulls',
    stadiumId: 'scottsmiracle-gro-field',
    openings: 12,
  },
  {
    id: 'm-2026-09-12-fc-dallas-portland-timbers',
    date: '2026-09-12',
    time: '7:30 PM CT',
    home: 'FC Dallas',
    away: 'Portland Timbers',
    stadiumId: 'toyota-stadium',
    openings: 15,
  },
  {
    id: 'm-2026-09-12-sporting-kansas-ci-lafc',
    date: '2026-09-12',
    time: '7:30 PM CT',
    home: 'Sporting Kansas City',
    away: 'LAFC',
    stadiumId: 'childrens-mercy-park',
    openings: 18,
  },
  {
    id: 'm-2026-09-12-st-louis-city-sc-minnesota-united-f',
    date: '2026-09-12',
    time: '7:30 PM CT',
    home: 'St. Louis CITY SC',
    away: 'Minnesota United FC',
    stadiumId: 'energizer-park',
    openings: 21,
  },
  {
    id: 'm-2026-09-12-colorado-rapids-cf-montréal',
    date: '2026-09-12',
    time: '7:30 PM MT',
    home: 'Colorado Rapids',
    away: 'CF Montréal',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 24,
  },
  {
    id: 'm-2026-09-12-real-salt-lake-new-york-city-fc',
    date: '2026-09-12',
    time: '7:30 PM MT',
    home: 'Real Salt Lake',
    away: 'New York City FC',
    stadiumId: 'america-first-field',
    openings: 10,
  },
  {
    id: 'm-2026-09-12-san-jose-earthquak-houston-dynamo-fc',
    date: '2026-09-12',
    time: '7:30 PM PT',
    home: 'San Jose Earthquakes',
    away: 'Houston Dynamo FC',
    stadiumId: 'paypal-park',
    openings: 13,
  },
  {
    id: 'm-2026-09-12-la-galaxy-seattle-sounders-f',
    date: '2026-09-12',
    time: '7:30 PM PT',
    home: 'LA Galaxy',
    away: 'Seattle Sounders FC',
    stadiumId: 'dignity-health-sports-park',
    openings: 16,
  },
  {
    id: 'm-2026-09-13-chicago-fire-fc-new-england-revolu',
    date: '2026-09-13',
    time: '6:30 PM ET',
    home: 'Chicago Fire FC',
    away: 'New England Revolution',
    stadiumId: 'soldier-field',
    openings: 19,
  },
  {
    id: 'm-2026-09-13-vancouver-whitecap-austin-fc',
    date: '2026-09-13',
    time: '6:30 PM PT',
    home: 'Vancouver Whitecaps FC',
    away: 'Austin FC',
    stadiumId: 'bc-place',
    openings: 22,
  },
  {
    id: 'm-2026-09-13-san-diego-fc-philadelphia-union',
    date: '2026-09-13',
    time: '9:00 PM ET',
    home: 'San Diego FC',
    away: 'Philadelphia Union',
    stadiumId: 'snapdragon-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-09-18-new-york-city-fc-new-york-red-bulls',
    date: '2026-09-18',
    time: '7:30 PM ET',
    home: 'New York City FC',
    away: 'New York Red Bulls',
    stadiumId: 'yankee-stadium',
    openings: 11,
  },
  {
    id: 'm-2026-09-19-new-england-revolu-orlando-city-sc',
    date: '2026-09-19',
    time: '7:30 PM ET',
    home: 'New England Revolution',
    away: 'Orlando City SC',
    stadiumId: 'gillette-stadium',
    openings: 14,
  },
  {
    id: 'm-2026-09-19-san-jose-earthquak-lafc',
    date: '2026-09-19',
    time: '7:30 PM PT',
    home: 'San Jose Earthquakes',
    away: 'LAFC',
    stadiumId: 'paypal-park',
    openings: 17,
  },
  {
    id: 'm-2026-09-19-cf-montréal-columbus-crew',
    date: '2026-09-19',
    time: '7:30 PM ET',
    home: 'CF Montréal',
    away: 'Columbus Crew',
    stadiumId: 'stade-saputo',
    openings: 20,
  },
  {
    id: 'm-2026-09-19-dc-united-charlotte-fc',
    date: '2026-09-19',
    time: '7:30 PM ET',
    home: 'D.C. United',
    away: 'Charlotte FC',
    stadiumId: 'audi-field',
    openings: 23,
  },
  {
    id: 'm-2026-09-19-houston-dynamo-fc-fc-cincinnati',
    date: '2026-09-19',
    time: '7:30 PM CT',
    home: 'Houston Dynamo FC',
    away: 'FC Cincinnati',
    stadiumId: 'shell-energy-stadium',
    openings: 9,
  },
  {
    id: 'm-2026-09-19-minnesota-united-f-la-galaxy',
    date: '2026-09-19',
    time: '7:30 PM CT',
    home: 'Minnesota United FC',
    away: 'LA Galaxy',
    stadiumId: 'allianz-field',
    openings: 12,
  },
  {
    id: 'm-2026-09-19-fc-dallas-austin-fc',
    date: '2026-09-19',
    time: '7:30 PM CT',
    home: 'FC Dallas',
    away: 'Austin FC',
    stadiumId: 'toyota-stadium',
    openings: 15,
  },
  {
    id: 'm-2026-09-19-sporting-kansas-ci-philadelphia-union',
    date: '2026-09-19',
    time: '7:30 PM CT',
    home: 'Sporting Kansas City',
    away: 'Philadelphia Union',
    stadiumId: 'childrens-mercy-park',
    openings: 18,
  },
  {
    id: 'm-2026-09-19-st-louis-city-sc-toronto-fc',
    date: '2026-09-19',
    time: '7:30 PM CT',
    home: 'St. Louis CITY SC',
    away: 'Toronto FC',
    stadiumId: 'energizer-park',
    openings: 21,
  },
  {
    id: 'm-2026-09-19-real-salt-lake-vancouver-whitecap',
    date: '2026-09-19',
    time: '7:30 PM MT',
    home: 'Real Salt Lake',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'america-first-field',
    openings: 24,
  },
  {
    id: 'm-2026-09-19-colorado-rapids-seattle-sounders-f',
    date: '2026-09-19',
    time: '7:30 PM MT',
    home: 'Colorado Rapids',
    away: 'Seattle Sounders FC',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 10,
  },
  {
    id: 'm-2026-09-19-nashville-sc-chicago-fire-fc',
    date: '2026-09-19',
    time: '7:30 PM CT',
    home: 'Nashville SC',
    away: 'Chicago Fire FC',
    stadiumId: 'geodis-park',
    openings: 13,
  },
  {
    id: 'm-2026-09-19-portland-timbers-atlanta-united-fc',
    date: '2026-09-19',
    time: '7:30 PM PT',
    home: 'Portland Timbers',
    away: 'Atlanta United FC',
    stadiumId: 'providence-park',
    openings: 16,
  },
  {
    id: 'm-2026-09-20-inter-miami-cf-san-diego-fc',
    date: '2026-09-20',
    time: '7:00 PM ET',
    home: 'Inter Miami CF',
    away: 'San Diego FC',
    stadiumId: 'nu-stadium',
    openings: 19,
  },
  {
    id: 'm-2026-09-23-seattle-sounders-f-real-salt-lake',
    date: '2026-09-23',
    time: '6:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'Real Salt Lake',
    stadiumId: 'lumen-field',
    openings: 22,
  },
  {
    id: 'm-2026-09-26-atlanta-united-fc-new-york-city-fc',
    date: '2026-09-26',
    time: '7:30 PM ET',
    home: 'Atlanta United FC',
    away: 'New York City FC',
    stadiumId: 'mercedes-benz-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-09-26-cf-montréal-fc-cincinnati',
    date: '2026-09-26',
    time: '7:30 PM ET',
    home: 'CF Montréal',
    away: 'FC Cincinnati',
    stadiumId: 'stade-saputo',
    openings: 11,
  },
  {
    id: 'm-2026-09-26-charlotte-fc-chicago-fire-fc',
    date: '2026-09-26',
    time: '7:30 PM ET',
    home: 'Charlotte FC',
    away: 'Chicago Fire FC',
    stadiumId: 'bank-of-america-stadium',
    openings: 14,
  },
  {
    id: 'm-2026-09-26-new-york-red-bulls-st-louis-city-sc',
    date: '2026-09-26',
    time: '7:30 PM ET',
    home: 'New York Red Bulls',
    away: 'St. Louis CITY SC',
    stadiumId: 'red-bull-arena',
    openings: 17,
  },
  {
    id: 'm-2026-09-26-philadelphia-union-orlando-city-sc',
    date: '2026-09-26',
    time: '7:30 PM ET',
    home: 'Philadelphia Union',
    away: 'Orlando City SC',
    stadiumId: 'subaru-park',
    openings: 20,
  },
  {
    id: 'm-2026-09-26-fc-dallas-lafc',
    date: '2026-09-26',
    time: '7:30 PM CT',
    home: 'FC Dallas',
    away: 'LAFC',
    stadiumId: 'toyota-stadium',
    openings: 23,
  },
  {
    id: 'm-2026-09-26-houston-dynamo-fc-sporting-kansas-ci',
    date: '2026-09-26',
    time: '7:30 PM CT',
    home: 'Houston Dynamo FC',
    away: 'Sporting Kansas City',
    stadiumId: 'shell-energy-stadium',
    openings: 9,
  },
  {
    id: 'm-2026-09-26-seattle-sounders-f-minnesota-united-f',
    date: '2026-09-26',
    time: '7:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'Minnesota United FC',
    stadiumId: 'lumen-field',
    openings: 12,
  },
  {
    id: 'm-2026-09-26-nashville-sc-toronto-fc',
    date: '2026-09-26',
    time: '7:30 PM CT',
    home: 'Nashville SC',
    away: 'Toronto FC',
    stadiumId: 'geodis-park',
    openings: 15,
  },
  {
    id: 'm-2026-09-26-austin-fc-san-diego-fc',
    date: '2026-09-26',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'San Diego FC',
    stadiumId: 'q2-stadium',
    openings: 18,
  },
  {
    id: 'm-2026-09-26-real-salt-lake-new-england-revolu',
    date: '2026-09-26',
    time: '7:30 PM MT',
    home: 'Real Salt Lake',
    away: 'New England Revolution',
    stadiumId: 'america-first-field',
    openings: 21,
  },
  {
    id: 'm-2026-09-26-la-galaxy-colorado-rapids',
    date: '2026-09-26',
    time: '7:30 PM PT',
    home: 'LA Galaxy',
    away: 'Colorado Rapids',
    stadiumId: 'dignity-health-sports-park',
    openings: 24,
  },
  {
    id: 'm-2026-09-26-vancouver-whitecap-dc-united',
    date: '2026-09-26',
    time: '7:30 PM PT',
    home: 'Vancouver Whitecaps FC',
    away: 'D.C. United',
    stadiumId: 'bc-place',
    openings: 10,
  },
  {
    id: 'm-2026-09-26-san-jose-earthquak-portland-timbers',
    date: '2026-09-26',
    time: '7:30 PM PT',
    home: 'San Jose Earthquakes',
    away: 'Portland Timbers',
    stadiumId: 'paypal-park',
    openings: 13,
  },
  {
    id: 'm-2026-09-27-columbus-crew-inter-miami-cf',
    date: '2026-09-27',
    time: '7:00 PM ET',
    home: 'Columbus Crew',
    away: 'Inter Miami CF',
    stadiumId: 'scottsmiracle-gro-field',
    openings: 16,
  },
  {
    id: 'm-2026-10-01-seattle-sounders-f-sporting-kansas-ci',
    date: '2026-10-01',
    time: '6:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'Sporting Kansas City',
    stadiumId: 'lumen-field',
    openings: 19,
  },
  {
    id: 'm-2026-10-06-chicago-fire-fc-vancouver-whitecap',
    date: '2026-10-06',
    time: '7:30 PM CT',
    home: 'Chicago Fire FC',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'soldier-field',
    openings: 22,
  },
  {
    id: 'm-2026-10-10-toronto-fc-cf-montréal',
    date: '2026-10-10',
    time: '1:00 PM ET',
    home: 'Toronto FC',
    away: 'CF Montréal',
    stadiumId: 'bmo-field',
    openings: 8,
  },
  {
    id: 'm-2026-10-10-chicago-fire-fc-new-york-city-fc',
    date: '2026-10-10',
    time: '1:30 PM CT',
    home: 'Chicago Fire FC',
    away: 'New York City FC',
    stadiumId: 'soldier-field',
    openings: 11,
  },
  {
    id: 'm-2026-10-10-inter-miami-cf-dc-united',
    date: '2026-10-10',
    time: '7:30 PM ET',
    home: 'Inter Miami CF',
    away: 'D.C. United',
    stadiumId: 'nu-stadium',
    openings: 14,
  },
  {
    id: 'm-2026-10-10-orlando-city-sc-columbus-crew',
    date: '2026-10-10',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'Columbus Crew',
    stadiumId: 'interco-stadium',
    openings: 17,
  },
  {
    id: 'm-2026-10-10-philadelphia-union-real-salt-lake',
    date: '2026-10-10',
    time: '7:30 PM ET',
    home: 'Philadelphia Union',
    away: 'Real Salt Lake',
    stadiumId: 'subaru-park',
    openings: 20,
  },
  {
    id: 'm-2026-10-10-atlanta-united-fc-fc-cincinnati',
    date: '2026-10-10',
    time: '7:30 PM ET',
    home: 'Atlanta United FC',
    away: 'FC Cincinnati',
    stadiumId: 'mercedes-benz-stadium',
    openings: 23,
  },
  {
    id: 'm-2026-10-10-new-england-revolu-seattle-sounders-f',
    date: '2026-10-10',
    time: '7:30 PM ET',
    home: 'New England Revolution',
    away: 'Seattle Sounders FC',
    stadiumId: 'gillette-stadium',
    openings: 9,
  },
  {
    id: 'm-2026-10-10-charlotte-fc-fc-dallas',
    date: '2026-10-10',
    time: '7:30 PM ET',
    home: 'Charlotte FC',
    away: 'FC Dallas',
    stadiumId: 'bank-of-america-stadium',
    openings: 12,
  },
  {
    id: 'm-2026-10-10-new-york-red-bulls-san-diego-fc',
    date: '2026-10-10',
    time: '7:30 PM ET',
    home: 'New York Red Bulls',
    away: 'San Diego FC',
    stadiumId: 'red-bull-arena',
    openings: 15,
  },
  {
    id: 'm-2026-10-10-minnesota-united-f-houston-dynamo-fc',
    date: '2026-10-10',
    time: '7:30 PM CT',
    home: 'Minnesota United FC',
    away: 'Houston Dynamo FC',
    stadiumId: 'allianz-field',
    openings: 18,
  },
  {
    id: 'm-2026-10-10-sporting-kansas-ci-portland-timbers',
    date: '2026-10-10',
    time: '7:30 PM CT',
    home: 'Sporting Kansas City',
    away: 'Portland Timbers',
    stadiumId: 'childrens-mercy-park',
    openings: 21,
  },
  {
    id: 'm-2026-10-10-austin-fc-nashville-sc',
    date: '2026-10-10',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'Nashville SC',
    stadiumId: 'q2-stadium',
    openings: 24,
  },
  {
    id: 'm-2026-10-10-colorado-rapids-san-jose-earthquak',
    date: '2026-10-10',
    time: '7:30 PM MT',
    home: 'Colorado Rapids',
    away: 'San Jose Earthquakes',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 10,
  },
  {
    id: 'm-2026-10-10-lafc-vancouver-whitecap',
    date: '2026-10-10',
    time: '7:30 PM PT',
    home: 'LAFC',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'bmo-stadium',
    openings: 13,
  },
  {
    id: 'm-2026-10-11-st-louis-city-sc-la-galaxy',
    date: '2026-10-11',
    time: '6:00 PM CT',
    home: 'St. Louis CITY SC',
    away: 'LA Galaxy',
    stadiumId: 'energizer-park',
    openings: 16,
  },
  {
    id: 'm-2026-10-14-toronto-fc-orlando-city-sc',
    date: '2026-10-14',
    time: '7:30 PM ET',
    home: 'Toronto FC',
    away: 'Orlando City SC',
    stadiumId: 'bmo-field',
    openings: 19,
  },
  {
    id: 'm-2026-10-14-inter-miami-cf-new-york-city-fc',
    date: '2026-10-14',
    time: '7:30 PM ET',
    home: 'Inter Miami CF',
    away: 'New York City FC',
    stadiumId: 'nu-stadium',
    openings: 22,
  },
  {
    id: 'm-2026-10-14-fc-cincinnati-new-england-revolu',
    date: '2026-10-14',
    time: '7:30 PM ET',
    home: 'FC Cincinnati',
    away: 'New England Revolution',
    stadiumId: 'tql-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-10-14-dc-united-new-york-red-bulls',
    date: '2026-10-14',
    time: '7:30 PM ET',
    home: 'D.C. United',
    away: 'New York Red Bulls',
    stadiumId: 'audi-field',
    openings: 11,
  },
  {
    id: 'm-2026-10-14-cf-montréal-atlanta-united-fc',
    date: '2026-10-14',
    time: '7:30 PM ET',
    home: 'CF Montréal',
    away: 'Atlanta United FC',
    stadiumId: 'stade-saputo',
    openings: 14,
  },
  {
    id: 'm-2026-10-14-columbus-crew-charlotte-fc',
    date: '2026-10-14',
    time: '7:30 PM ET',
    home: 'Columbus Crew',
    away: 'Charlotte FC',
    stadiumId: 'scottsmiracle-gro-field',
    openings: 17,
  },
  {
    id: 'm-2026-10-14-nashville-sc-sporting-kansas-ci',
    date: '2026-10-14',
    time: '7:30 PM CT',
    home: 'Nashville SC',
    away: 'Sporting Kansas City',
    stadiumId: 'geodis-park',
    openings: 20,
  },
  {
    id: 'm-2026-10-14-fc-dallas-seattle-sounders-f',
    date: '2026-10-14',
    time: '7:30 PM CT',
    home: 'FC Dallas',
    away: 'Seattle Sounders FC',
    stadiumId: 'toyota-stadium',
    openings: 23,
  },
  {
    id: 'm-2026-10-14-st-louis-city-sc-vancouver-whitecap',
    date: '2026-10-14',
    time: '7:30 PM CT',
    home: 'St. Louis CITY SC',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'energizer-park',
    openings: 9,
  },
  {
    id: 'm-2026-10-14-chicago-fire-fc-philadelphia-union',
    date: '2026-10-14',
    time: '7:30 PM CT',
    home: 'Chicago Fire FC',
    away: 'Philadelphia Union',
    stadiumId: 'soldier-field',
    openings: 12,
  },
  {
    id: 'm-2026-10-14-real-salt-lake-san-jose-earthquak',
    date: '2026-10-14',
    time: '7:30 PM MT',
    home: 'Real Salt Lake',
    away: 'San Jose Earthquakes',
    stadiumId: 'america-first-field',
    openings: 15,
  },
  {
    id: 'm-2026-10-14-colorado-rapids-minnesota-united-f',
    date: '2026-10-14',
    time: '7:30 PM MT',
    home: 'Colorado Rapids',
    away: 'Minnesota United FC',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 18,
  },
  {
    id: 'm-2026-10-14-san-diego-fc-houston-dynamo-fc',
    date: '2026-10-14',
    time: '7:30 PM PT',
    home: 'San Diego FC',
    away: 'Houston Dynamo FC',
    stadiumId: 'snapdragon-stadium',
    openings: 21,
  },
  {
    id: 'm-2026-10-14-lafc-austin-fc',
    date: '2026-10-14',
    time: '7:30 PM PT',
    home: 'LAFC',
    away: 'Austin FC',
    stadiumId: 'bmo-stadium',
    openings: 24,
  },
  {
    id: 'm-2026-10-14-la-galaxy-portland-timbers',
    date: '2026-10-14',
    time: '7:30 PM PT',
    home: 'LA Galaxy',
    away: 'Portland Timbers',
    stadiumId: 'dignity-health-sports-park',
    openings: 10,
  },
  {
    id: 'm-2026-10-17-philadelphia-union-charlotte-fc',
    date: '2026-10-17',
    time: '2:30 PM ET',
    home: 'Philadelphia Union',
    away: 'Charlotte FC',
    stadiumId: 'subaru-park',
    openings: 13,
  },
  {
    id: 'm-2026-10-17-minnesota-united-f-st-louis-city-sc',
    date: '2026-10-17',
    time: '3:30 PM CT',
    home: 'Minnesota United FC',
    away: 'St. Louis CITY SC',
    stadiumId: 'allianz-field',
    openings: 16,
  },
  {
    id: 'm-2026-10-17-new-york-red-bulls-toronto-fc',
    date: '2026-10-17',
    time: '7:30 PM ET',
    home: 'New York Red Bulls',
    away: 'Toronto FC',
    stadiumId: 'red-bull-arena',
    openings: 19,
  },
  {
    id: 'm-2026-10-17-new-england-revolu-chicago-fire-fc',
    date: '2026-10-17',
    time: '7:30 PM ET',
    home: 'New England Revolution',
    away: 'Chicago Fire FC',
    stadiumId: 'gillette-stadium',
    openings: 22,
  },
  {
    id: 'm-2026-10-17-atlanta-united-fc-inter-miami-cf',
    date: '2026-10-17',
    time: '7:30 PM ET',
    home: 'Atlanta United FC',
    away: 'Inter Miami CF',
    stadiumId: 'mercedes-benz-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-10-17-orlando-city-sc-dc-united',
    date: '2026-10-17',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'D.C. United',
    stadiumId: 'interco-stadium',
    openings: 11,
  },
  {
    id: 'm-2026-10-17-austin-fc-vancouver-whitecap',
    date: '2026-10-17',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'q2-stadium',
    openings: 14,
  },
  {
    id: 'm-2026-10-17-houston-dynamo-fc-fc-dallas',
    date: '2026-10-17',
    time: '7:30 PM CT',
    home: 'Houston Dynamo FC',
    away: 'FC Dallas',
    stadiumId: 'shell-energy-stadium',
    openings: 17,
  },
  {
    id: 'm-2026-10-17-sporting-kansas-ci-real-salt-lake',
    date: '2026-10-17',
    time: '7:30 PM CT',
    home: 'Sporting Kansas City',
    away: 'Real Salt Lake',
    stadiumId: 'childrens-mercy-park',
    openings: 20,
  },
  {
    id: 'm-2026-10-17-seattle-sounders-f-cf-montréal',
    date: '2026-10-17',
    time: '7:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'CF Montréal',
    stadiumId: 'lumen-field',
    openings: 23,
  },
  {
    id: 'm-2026-10-17-san-jose-earthquak-nashville-sc',
    date: '2026-10-17',
    time: '7:30 PM PT',
    home: 'San Jose Earthquakes',
    away: 'Nashville SC',
    stadiumId: 'paypal-park',
    openings: 9,
  },
  {
    id: 'm-2026-10-17-la-galaxy-san-diego-fc',
    date: '2026-10-17',
    time: '7:30 PM PT',
    home: 'LA Galaxy',
    away: 'San Diego FC',
    stadiumId: 'dignity-health-sports-park',
    openings: 12,
  },
  {
    id: 'm-2026-10-17-portland-timbers-colorado-rapids',
    date: '2026-10-17',
    time: '7:30 PM PT',
    home: 'Portland Timbers',
    away: 'Colorado Rapids',
    stadiumId: 'providence-park',
    openings: 15,
  },
  {
    id: 'm-2026-10-18-fc-cincinnati-columbus-crew',
    date: '2026-10-18',
    time: '7:00 PM ET',
    home: 'FC Cincinnati',
    away: 'Columbus Crew',
    stadiumId: 'tql-stadium',
    openings: 18,
  },
  {
    id: 'm-2026-10-24-cf-montréal-nashville-sc',
    date: '2026-10-24',
    time: '1:30 PM ET',
    home: 'CF Montréal',
    away: 'Nashville SC',
    stadiumId: 'stade-saputo',
    openings: 21,
  },
  {
    id: 'm-2026-10-24-columbus-crew-toronto-fc',
    date: '2026-10-24',
    time: '3:30 PM ET',
    home: 'Columbus Crew',
    away: 'Toronto FC',
    stadiumId: 'scottsmiracle-gro-field',
    openings: 24,
  },
  {
    id: 'm-2026-10-24-new-york-red-bulls-inter-miami-cf',
    date: '2026-10-24',
    time: '5:30 PM ET',
    home: 'New York Red Bulls',
    away: 'Inter Miami CF',
    stadiumId: 'red-bull-arena',
    openings: 10,
  },
  {
    id: 'm-2026-10-24-orlando-city-sc-new-york-city-fc',
    date: '2026-10-24',
    time: '7:30 PM ET',
    home: 'Orlando City SC',
    away: 'New York City FC',
    stadiumId: 'interco-stadium',
    openings: 13,
  },
  {
    id: 'm-2026-10-24-atlanta-united-fc-chicago-fire-fc',
    date: '2026-10-24',
    time: '7:30 PM ET',
    home: 'Atlanta United FC',
    away: 'Chicago Fire FC',
    stadiumId: 'mercedes-benz-stadium',
    openings: 16,
  },
  {
    id: 'm-2026-10-24-philadelphia-union-new-england-revolu',
    date: '2026-10-24',
    time: '7:30 PM ET',
    home: 'Philadelphia Union',
    away: 'New England Revolution',
    stadiumId: 'subaru-park',
    openings: 19,
  },
  {
    id: 'm-2026-10-24-dc-united-fc-cincinnati',
    date: '2026-10-24',
    time: '7:30 PM ET',
    home: 'D.C. United',
    away: 'FC Cincinnati',
    stadiumId: 'audi-field',
    openings: 22,
  },
  {
    id: 'm-2026-10-24-houston-dynamo-fc-minnesota-united-f',
    date: '2026-10-24',
    time: '7:30 PM CT',
    home: 'Houston Dynamo FC',
    away: 'Minnesota United FC',
    stadiumId: 'shell-energy-stadium',
    openings: 8,
  },
  {
    id: 'm-2026-10-24-colorado-rapids-vancouver-whitecap',
    date: '2026-10-24',
    time: '6:30 PM MT',
    home: 'Colorado Rapids',
    away: 'Vancouver Whitecaps FC',
    stadiumId: 'dicks-sporting-goods-park',
    openings: 11,
  },
  {
    id: 'm-2026-10-24-real-salt-lake-st-louis-city-sc',
    date: '2026-10-24',
    time: '6:30 PM MT',
    home: 'Real Salt Lake',
    away: 'St. Louis CITY SC',
    stadiumId: 'america-first-field',
    openings: 14,
  },
  {
    id: 'm-2026-10-24-sporting-kansas-ci-austin-fc',
    date: '2026-10-24',
    time: '7:30 PM CT',
    home: 'Sporting Kansas City',
    away: 'Austin FC',
    stadiumId: 'childrens-mercy-park',
    openings: 17,
  },
  {
    id: 'm-2026-10-24-fc-dallas-san-jose-earthquak',
    date: '2026-10-24',
    time: '7:30 PM CT',
    home: 'FC Dallas',
    away: 'San Jose Earthquakes',
    stadiumId: 'toyota-stadium',
    openings: 20,
  },
  {
    id: 'm-2026-10-24-san-diego-fc-seattle-sounders-f',
    date: '2026-10-24',
    time: '7:30 PM PT',
    home: 'San Diego FC',
    away: 'Seattle Sounders FC',
    stadiumId: 'snapdragon-stadium',
    openings: 23,
  },
  {
    id: 'm-2026-10-24-portland-timbers-charlotte-fc',
    date: '2026-10-24',
    time: '7:30 PM PT',
    home: 'Portland Timbers',
    away: 'Charlotte FC',
    stadiumId: 'providence-park',
    openings: 9,
  },
  {
    id: 'm-2026-10-25-lafc-la-galaxy',
    date: '2026-10-25',
    time: '6:00 PM PT',
    home: 'LAFC',
    away: 'LA Galaxy',
    stadiumId: 'bmo-stadium',
    openings: 12,
  },
  {
    id: 'm-2026-10-28-new-york-city-fc-atlanta-united-fc',
    date: '2026-10-28',
    time: '7:30 PM ET',
    home: 'New York City FC',
    away: 'Atlanta United FC',
    stadiumId: 'yankee-stadium',
    openings: 15,
  },
  {
    id: 'm-2026-10-28-toronto-fc-dc-united',
    date: '2026-10-28',
    time: '7:30 PM ET',
    home: 'Toronto FC',
    away: 'D.C. United',
    stadiumId: 'bmo-field',
    openings: 18,
  },
  {
    id: 'm-2026-10-28-charlotte-fc-cf-montréal',
    date: '2026-10-28',
    time: '7:30 PM ET',
    home: 'Charlotte FC',
    away: 'CF Montréal',
    stadiumId: 'bank-of-america-stadium',
    openings: 21,
  },
  {
    id: 'm-2026-10-28-inter-miami-cf-fc-cincinnati',
    date: '2026-10-28',
    time: '7:30 PM ET',
    home: 'Inter Miami CF',
    away: 'FC Cincinnati',
    stadiumId: 'nu-stadium',
    openings: 24,
  },
  {
    id: 'm-2026-10-28-new-england-revolu-new-york-red-bulls',
    date: '2026-10-28',
    time: '7:30 PM ET',
    home: 'New England Revolution',
    away: 'New York Red Bulls',
    stadiumId: 'gillette-stadium',
    openings: 10,
  },
  {
    id: 'm-2026-10-28-austin-fc-real-salt-lake',
    date: '2026-10-28',
    time: '7:30 PM CT',
    home: 'Austin FC',
    away: 'Real Salt Lake',
    stadiumId: 'q2-stadium',
    openings: 13,
  },
  {
    id: 'm-2026-10-28-chicago-fire-fc-orlando-city-sc',
    date: '2026-10-28',
    time: '7:30 PM CT',
    home: 'Chicago Fire FC',
    away: 'Orlando City SC',
    stadiumId: 'soldier-field',
    openings: 16,
  },
  {
    id: 'm-2026-10-28-fc-dallas-columbus-crew',
    date: '2026-10-28',
    time: '7:30 PM CT',
    home: 'FC Dallas',
    away: 'Columbus Crew',
    stadiumId: 'toyota-stadium',
    openings: 19,
  },
  {
    id: 'm-2026-10-28-minnesota-united-f-sporting-kansas-ci',
    date: '2026-10-28',
    time: '7:30 PM CT',
    home: 'Minnesota United FC',
    away: 'Sporting Kansas City',
    stadiumId: 'allianz-field',
    openings: 22,
  },
  {
    id: 'm-2026-10-28-nashville-sc-philadelphia-union',
    date: '2026-10-28',
    time: '7:30 PM CT',
    home: 'Nashville SC',
    away: 'Philadelphia Union',
    stadiumId: 'geodis-park',
    openings: 8,
  },
  {
    id: 'm-2026-10-28-st-louis-city-sc-portland-timbers',
    date: '2026-10-28',
    time: '7:30 PM CT',
    home: 'St. Louis CITY SC',
    away: 'Portland Timbers',
    stadiumId: 'energizer-park',
    openings: 11,
  },
  {
    id: 'm-2026-10-28-seattle-sounders-f-houston-dynamo-fc',
    date: '2026-10-28',
    time: '7:30 PM PT',
    home: 'Seattle Sounders FC',
    away: 'Houston Dynamo FC',
    stadiumId: 'lumen-field',
    openings: 14,
  },
];
